- src/tokens/mainnet-beta.json
two MAPS in the list, delete one.
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Other information**:
> two MAPS in the list, delete one.

- src/lib/tokens.ts
- src/tokens/mainnet-beta.json
- **What kind of change does this PR introduce?** 
- Added tokens to registry from Explorer.
- Added optional website to KnownToken interface.
> introduce additional tokens from solana-labs/explorer

- src/tokens/mainnet-beta.json
> add LSD name

- src/tokens/mainnet-beta.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
add logo
- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Other information**:
Add BitSong logo to token list
> Add bitsong

- README.md
- package-lock.json
- src/index.ts
- src/lib/tokenlist.spec.ts
- src/lib/tokenlist.ts
- src/tokens/solana.tokenlist.json
Initial draft of tokenlist standard with TokenListProvider.
> feat: initial commit of tokenlist format

- src/lib/tokenlist.ts
Minor cleanup, fluent interface where original object is unmodified.
> feat: modify fluent interface to return new token list container

- src/lib/tokenlist.ts
- src/tokens/solana.tokenlist.json
Update extensions type definition and rename bridge-contract to camel case.
> rename bridge contract member and update json

- src/tokens/solana.tokenlist.json
Missing info from the sollet token list. Required for https://github.com/project-serum/spl-token-wallet/pull/141/files.
> Add missing sollet tokens

- src/tokens/solana.tokenlist.json
> fix: update USDT logo

- src/tokens/solana.tokenlist.json
fix: point to master for trustwallet assets
> fix: point to master for trustwallet assets

- src/tokens/solana.tokenlist.json
> Adding doce finance token to list

- src/tokens/solana.tokenlist.json
* Token Name: 
* Logo (n/a - still being processed)
* Link to the official homepage of token: (n/a)
> Add Hedgehog testnet token to the list.

- src/tokens/solana.tokenlist.json
> Added two new Kreechure NFTs to the list

- .vscode/settings.json
- src/tokens/solana.tokenlist.json
> Add Raydium LP tokens and use json formatter for vscode

- src/tokens/solana.tokenlist.json
* Token Address:  6ybxMQpMgQhtsTLhvHZqk8uqao7kvoexY6e8JmCTqAB1
* Token Name:  QOIN
* Token Symbol:  QOIN
* Logo https://coin-chest.com/qoin_logo500x500.png
* Link to the official homepage of token: https://coin-chest.com
> QOIN added

- src/tokens/solana.tokenlist.json
_**Please provide the following information for your token:**_
$ROPE is a full-scale decentralized ecosystem that brings the well-known "market volatility index" to the crypto market.
This PR will simply add Rope Token to the token list.
```
{
"chainId": 101,
"address": "8PMHT4swUMtBzgHnh5U564N5sjPSiUz2cjEQzFnnP1Fo",
"symbol": "ROPE",
"name": "Rope Token",
"decimals": 9,
"logoURI": "https://ropesolana.com/content/files/rope_33_1.svg",
"tags": [],
"extensions": {
"website": "https://ropesolana.com/"
}
},
```
* Token Address: 8PMHT4swUMtBzgHnh5U564N5sjPSiUz2cjEQzFnnP1Fo
* Token Name: Rope Token
* Token Symbol: ROPE
* Logo: [https://ropesolana.com/content/files/rope_33_1.svg](https://ropesolana.com/content/files/rope_33_1.svg) …
> Added Rope Token (ROPE) to token list.

- src/tokens/solana.tokenlist.json
* Token Address: 5dhkWqrq37F92jBmEyhQP1vbMkbVRz59V7288HH2wBC7
* Token Name: SOLLock
* Token Symbol: SLOCK
* Logo: https://sollock.io/token/sollock_icon.png
* Link to the official homepage of token: https://sollock.io/
> added SOLLock "SLOCK" to the list

- src/tokens/solana.tokenlist.json
* Token Address: 6ybxMQpMgQhtsTLhvHZqk8uqao7kvoexY6e8JmCTqAB1
* Token Name: QUEST
* Token Symbol: QUEST
* Logo: https://questcoin.org/logo500x500.png
* Link to the official homepage of token: https://questcoin.org
> QOIN edited name and symbol added website address

- src/tokens/solana.tokenlist.json
Adding RECO token :). Thanks
* Token Address: **2rEiLkpQ3mh4DGxv1zcSdW5r5HK2nehif5sCaF5Ss9E1**
* Token Name: **Reboot ECO**
* Token Symbol: **RECO**
* Logo : https://reboot.eco/reco_logo.png
* Link to the official homepage of token: https://reboot.eco/
Thanks !
> Adding RECO token

- src/lib/tokenlist.ts
Added
TokenExtensions
*Twitter - "twitter"
*Github - "github"
*Medium - "medium"
*Telegram Announcement - "tgann"
*Telegram Group - "tggroup"
*Discord - "discord"
* Token Name: 
* Logo
> Added useful token extensions

- src/tokens/solana.tokenlist.json
Added
Tags:
*Security Token - Tokens that are used to gain access to an electronically restricted resource
*Utility Tokens - Tokens that are designed to be spent within a certain blockchain ecosystem e.g. most of the SPL-Tokens
-----------------------------------------
Changed SOLLock tag to "utility-token"
Added useful TokenExtensions
*Twitter
*Github
*Telegram Ann
*Telegram Group
* Token Name: 
* Logo
> Added Tags for Utility & Security Tokens

- .cspell.json
Fixes cspell errors with new extension types
> fix: add tgann and tggroup to cspell words

- src/tokens/solana.tokenlist.json
> Add Star Atlas DOI token

- src/tokens/solana.tokenlist.json
Hello, I have made a mistake in the link of the PNG of the Samoyed Coin, so I changed it, is it possible to update it please ?
Thank you ! :)
> Update logo link of Samoyed Coin

- src/tokens/solana.tokenlist.json
* Token Address: 8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s
* Token Name: SolDoge
* Token Symbol: SDOGE
* Logo: https://pbs.twimg.com/profile_images/1386711926571364352/UfsqsIB3_400x400.jpg
* Link to the official homepage of token: https://soldoge.org
> Add sol doge

- src/tokens/solana.tokenlist.json
> update USDC logo in tokenlist.json

- .github/PULL_REQUEST_TEMPLATE.md
- src/lib/tokenlist.ts
- src/tokens/solana.tokenlist.json
> Add coingeckoId to the extension field of some coins

- src/tokens/solana.tokenlist.json
> fix: add branch to jsdelivr

- src/tokens/solana.tokenlist.json
Dominican Pesos duplicate address with less information was removed.
> Removed duplicate Dominican Pesos

- src/tokens/solana.tokenlist.json
> Add Hungry Token

- src/tokens/solana.tokenlist.json
[x] I will not ping the Discord about this pull request.
Token Address: 8GQsW3f7mdwfjqJon2myADcBsSsRjpXmxHYDG8q1pvV6
Token Name: Holdana
Token Symbol: Hold
Logo: https://i.ibb.co/7CWsB34/holdana-token.png
Website will soon be released. Meanwhile, twitter = https://twitter.com/HoldanaOfficial
> Added Holdana token

- src/tokens/solana.tokenlist.json
* Token Address: AByXcTZwJHMtrKrvVsh9eFNB1pJaLDjCUR2ayvxBAAM2
* Token Name: Wrapped Strong (Sollet)
* Token Symbol: STRONG
* Logo: https://cdn.jsdelivr.net/gh/trustwallet/assets@master/blockchains/ethereum/assets/0x990f341946A3fdB507aE7e52d17851B87168017c/logo.png
* Link to the official homepage of token: https://strongblock.com/
* Coingecko ID: strong (https://api.coingecko.com/api/v3/coins/strong)
> strongblock_addition

- src/tokens/solana.tokenlist.json
* Token Address:  xuNGfwG8r3CEubQcssj3A7zoZwb4NaiamhHsJEMt7kf
* Token Name: Synthetify
* Token Symbol: SNY
* Logo: https://resources.synthetify.io/sythetify.png
* Link to the official homepage of token: https://synthetify.io/
> add Synthetify SNY

- src/tokens/solana.tokenlist.json
> Adding as many coingeckoIds as possible

- src/tokens/solana.tokenlist.json
* Token Address: 4wTMJsh3q66PmAkmwEW47qVDevMZMVVWU3n1Yhqztwi6
* Token Name: Arcade Token (Wormhole)
* Token Symbol: ARCD
* Logo: https://arcade.city/img/ARCD200.png
* Link to the official homepage of token: https://arcade.city
* Coingecko ID if available - none yet
> Add Arcade Token (ARCD)

- src/tokens/solana.tokenlist.json
Added Stonks token
Icon: PNG, 250x250px, hosted on GitHub.
* Token Address: ```43VWkd99HjqkhFTZbWBpMpRhjG469nWa7x7uEsgSH7We```
* Token Name: ```Stonks```
* Token Symbol: ```STNK```
* Logo ```https://raw.githubusercontent.com/StonksDev/Resource/main/StonksIcon250.png```
* Link to the official homepage of token: [https://stonkscoin.org](url)
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): ```None```
> Added Stonks token

- src/tokens/solana.tokenlist.json
* Token Address: Amt5wUJREJQC5pX7Z48YSK812xmu4j3sQVupNhtsEuY8
* Token Name: FROG
* Token Symbol: FROG
* Logo: https://raw.githubusercontent.com/FROG-SPL/branding/main/the_frauge_finifhes.jpeg
* Link to the official homepage of token: https://www.frogsolana.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): TBD
> Add FROG Token

- src/tokens/solana.tokenlist.json
Remove extra comma, that breaks the JSON format
> Fix solana.tokenlist.json

- src/tokens/solana.tokenlist.json
> Add TCW token

- src/tokens/solana.tokenlist.json
- [ x] I will not ping the Discord about this pull request.
* Token Name: 
* Logo
> Add correct decimals to COPE

- src/tokens/solana.tokenlist.json
* Token Address: MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K
* Token Name: Mercurial
* Token Symbol: MER
* Logo: https://www.mercurial.finance/mercurial-explorer-logo.svg
* Link to the official homepage of token: https://www.mercurial.finance/
> Add Mercurial (MER) Token٩(^ᴗ^)۶

- src/tokens/solana.tokenlist.json
* Token Address: Amt5wUJREJQC5pX7Z48YSK812xmu4j3sQVupNhtsEuY8
* Token Name: FROG
* Token Symbol: FROG
* Logo: https://raw.githubusercontent.com/FROG-SPL/branding/main/the_frauge_finifhes.jpeg
* Link to the official homepage of token: https://www.froglana.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): TBD
> FROG Website URL Update

- src/tokens/solana.tokenlist.json
mBRZ
* Token Address: Bxp46xCB6CLjiqE99QaTcJAaY1hYF1o63DUUrXAS7QFu
* Token Name: SolMiner Bronze
* Token Symbol: mBRZ
* Logo : https://i.ibb.co/Wcxc7K7/solminer-bronze.png
* Link to the official homepage of token: https://solminer.app
* 
mPLAT
* Token Address: GZNrMEdrt6Vg428JzvJYRGGPpVxgjUPsg6WLqKBvmNLw
* Token Name: SolMiner Platinum
* Token Symbol: mPLAT
* Logo : https://i.ibb.co/vYkMprc/solminer-platinum.png
* Link to the official homepage of token: https://solminer.app
mDIAM
* Token Address: Er7a3ugS6kkAqj6sp3UmXEFAFrDdLMRQEkV9QH2fwRYA
* Token Name: SolMiner Diamond
* Token Symbol: mDIAM
* Logo : https://i.ibb.co/rtvKFHn/solminer-diamond.png
* Link to the official homepage of token: https://solminer.app
> Add mBRZ, mPLAT and mDIAM tokens

- src/tokens/solana.tokenlist.json
> APYSwap token added

- src/tokens/solana.tokenlist.json
> Adds additional Star Atlas poster NFT mints

- src/tokens/solana.tokenlist.json
Token Address: nope9HWCJcXVFkG49CDk7oYFtgGsUzsRvHdcJeL2aCL
Token Name: NOPE FINANCE
Token Symbol: NOPE
Logo: https://raw.githubusercontent.com/nopefinance/nope-land/main/icon.png
Link to the official homepage of token: https://nopefinance.xyz/
> adding NOPE Finance token :)

- src/tokens/solana.tokenlist.json
* Token Address: TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs
* Token Name: Tulip
* Token Symbol: TULIP
* Logo: https://solfarm.io/solfarm-logo.svg
* Link to the official homepage of token: https://solfarm.io
> Add solfarm token 🌷

- src/tokens/solana.tokenlist.json
* Token Address: SolaPAD
* Token Name: SOLA
* Token Symbol: 8
* Logo: https://i.ibb.co/3p4SMBd/LOGO.png
* Link to the official homepage of token: https://www.solapad.org/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): not listed
> Add SolaPAD token

- src/tokens/solana.tokenlist.json
Domain changed and server changed to accommodate more users who can access the site and won't slow down the site. And we also managed to add more security firewall for the website in order to be fully accessible all the time.
* Token Name: 
* Logo
> Updates website domain for SOLLock

- src/tokens/solana.tokenlist.json
* Token Address: 5trVBqv1LvHxiSPMsHtEZuf8iN82wbpDcR5Zaw7sWC3s
* Token Name: JPY Coin
* Token Symbol: JPYC
* Logo: https://raw.githubusercontent.com/jpycoin/jpyc/main/src/image/jpyc.png
* Link to the official homepage of token: https://jpyc.jp/
> Add JPY Coin Token

- src/tokens/solana.tokenlist.json
> APYSwap token URL fixed

- src/tokens/solana.tokenlist.json
* Token Address: 9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE
* Token Name: WOOFENOMICS
* Token Symbol: WOOF
* Logo: https://i.ibb.co/sHb9qZj/woof-orange-black.png
* Link to the official homepage of token: https://www.woofsolana.com/
> Add WOOF Token

- src/tokens/solana.tokenlist.json
* Token Address: 3QuAYThYKFXSmrTcSHsdd7sAxaFBobaCkLy2DBYJLMDs
* Token Name: wTYNA
* Token Symbol: TYNA
* Logo: https://raw.githubusercontent.com/M-Igashi/FTX-GAS-Tools/main/icon384.png
* Link to the official homepage of token: http://lendingbot.s3-website-us-east-1.amazonaws.com/whitepaper.html
> Adding wTYNA

- src/tokens/solana.tokenlist.json
* Token Address:  7zsKqN7Fg2s9VsqAq6XBoiShCVohpGshSUvoWBc6jKYh
* Token Name:  Wrapped ArdCoin (Sollet)
* Token Symbol: ARDX
* Logo: https://cdn.dex.mn/logo/ardx.png
* Link to the official homepage of token: https://ardcoin.com/
> Wrapped ArdCoin added

- src/tokens/solana.tokenlist.json
* Token Address: MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K
* Token Name: Mercurial
* Token Symbol: MER
* Link to the official homepage of token: https://www.mercurial.finance/
* Coingecko ID if available: mercurial
> MER: add coingeckoId.

- src/tokens/solana.tokenlist.json
1. Fix some typo 
-`serumV3Udsc` -> `serumV3Usdc` 
2. Update Coingecko Id to match https://api.coingecko.com/api/v3/coins/list"
3. Add `serumV3Usdc` address for some tokens
> Update wrong coingecko id and serum market address

- src/tokens/solana.tokenlist.json
> Token-list PRs 148 - 215

- src/tokens/solana.tokenlist.json
* Token Address: 8s9FCz99Wcr3dHpiauFRi6bLXzshXfcGTfgQE7UEopVx
* Token Name: ChikinCoin
* Token Symbol: CKC
* Logo: https://raw.githubusercontent.com/ChikinDeveloper/ChikinCoin/master/assets/logo_colored.svg
* Link to the official homepage of token: https://www.chikin.run
> Add chikincoin to token list

- src/lib/tokenlist.ts
> Add imageUrl and description to TokenExtensions

- src/tokens/solana.tokenlist.json
* Token Address: 8s9FCz99Wcr3dHpiauFRi6bLXzshXfcGTfgQE7UEopVx
* Token Name: ChikinCoin
* Token Symbol: CKC
* Logo: https://raw.githubusercontent.com/ChikinDeveloper/ChikinCoin/master/assets/logo_circle.svg
* Link to the official homepage of token: https://www.chikin.run
> Replace ChikinCoin logoURI with circle logo

- src/tokens/solana.tokenlist.json
- Fix solfarm coingecko id, `tulip-token` -> `solfarm`
> fix solfarm coingecko id

- src/tokens/solana.tokenlist.json
* Token Address: 2doeZGLJyACtaG9DCUyqMLtswesfje1hjNA11hMdj6YU
* Token Name: Raydium LP Token V4 (TULIP-USDC)
* Token Symbol: TULIP-USDC
* Logo: https://solfarm.io/tulip-usdc.svg
* Link to the official homepage of token: https://solfarm.io
> add tulip-usdc lp token

- src/lib/tokenlist.ts
- src/tokens/solana.tokenlist.json
Updates the symbol of Wrapped SOL from SOL to wSOL
> Update wrapped sol

- src/tokens/solana.tokenlist.json
* Token Address: 4NPzwMK2gfgQ6rTv8x4EE1ZvKW6MYyYTSrAZCx7zxyaX
* Token Name: Black Label
* Token Symbol: KLB
* Logo: https://raw.githubusercontent.com/klbtoken/klbtoken/main/klbtoken.svg
* Link to the official homepage of token: https://klbtoken.com
> Add KLB Token

- src/tokens/solana.tokenlist.json
Remove duplicate from https://github.com/solana-labs/token-list/pull/173 causes "key" errors in React
> refactor: remove SolaPAD Token duplicate

- src/tokens/solana.tokenlist.json
* Token Address: 3RSafdgu7P2smSGHJvSGQ6kZVkcErZXfZTtynJYboyAu
* Token Name: SINE
* Token Symbol: SINE
* Logo: https://raw.githubusercontent.com/sinetoken/public/main/icon/circle_icon/circle_icon.svg
* Link to the official homepage of token: https://solainetwork.com/
> Add SINE token

- src/tokens/solana.tokenlist.json
* Token Address: 51tMb3zBKDiQhNwGqpgwbavaGH54mk8fXFzxTc1xnasg
* Token Name: APEX
* Token Symbol: APEX
* Logo: https://apexit.finance/images/apex.png
* Link to the official homepage of token: https://apexit.finance
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): N/A
> Add APEX to token list

- src/tokens/solana.tokenlist.json
Token Address: 97qAF7ZKEdPdQaUkhASGA59Jpa2Wi7QqVmnFdEuPqEDc
Token Name: DIAMOND
Token Symbol: LOVE
Logo https://github.com/AdamBraham88/SPL-TOKEN/blob/main/Diamond-Love-icon.png
Link to the official homepage of token: https://diamondlove.io
Tags": Diamond Love
> ADD DIAMOND LOVE TOKEN

- .github/PULL_REQUEST_TEMPLATE.md
Noticed that the referenced file was not showing up properly, so I changed it to what I believe is the file you wanted to reference.
> Fix referenced file on Pull request template

- src/tokens/solana.tokenlist.json
> Add Serum USDC and USDT stable swap market

- src/tokens/solana.tokenlist.json
Updating info for STEP and some missing Serum market ID's for a few other tokens.
> Add some missing serum market ID's

- src/tokens/solana.tokenlist.json
* Token Name: 
* Logo: https://i.ibb.co/YPyhnkS/Bole.jpg
> Fix BOLE token logo url

- src/tokens/solana.tokenlist.json
Hey, Neil from the $FTR Future team here. Would be very happy to see this push accepted so our holders can see the name and logo of their favorite SPL token in their solana wallet :) . Hope we did everything right, don't hesitate to reach us on https://twitter.com/ftr_finance or on our discord : https://discord.gg/GC9nqsSa
Thanks a lot for all the work provided building the sol blockchain and ecosystem. LONG LIVE SOL, LONG LIVE THE DEV <3
* Token Address: HEhMLvpSdPviukafKwVN8BnBUTamirptsQ6Wxo5Cyv8s
* Token Name: FUTURE
* Token Symbol: FTR
* Logo : http://future-ftr.io/images/logo.png …
> Add the FTR Future token to solana.tokenlist.json

- src/tokens/solana.tokenlist.json
*Token Address: 6kwTqmdQkJd8qRr9RjSnUX9XJ24RmJRSrU1rsragP97Y
*Token Name: SAIL
*Token Symbol: : SAIL
*Logo : https://cloudflare-ipfs.com/ipfs/QmPcQfofQNfiv36EAsGQrgAhiPbqGf17i1Cz648JhXFW9m/logo_solana_sail_v2.png
*Link to the official homepage of token: https://www.solanasail.com
*Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):
> add SAIL to token list

- src/tokens/solana.tokenlist.json
Hey, this is cryptocurrencies.ai team reaching out. It would be great if you'll help us add our token to the list. If there are any issues, please contact us via our site https://cryptocurrencies.ai/contact or Twitter https://twitter.com/CCAI_Official.
Hope to hear from you soon.
* Token Address: E5ndSkaB17Dm7CsD22dvcjfrYSDLCxFcMd6z8ddCk5wp
* Token Name: Cryptocurrencies.Ai
* Token Symbol: CCAI
* Logo: https://cryptocurrencies.ai/logo.png
* Link to the official homepage of token: https://ccai.cryptocurrencies.ai
> Add the CCAI Cryptocurrencies.Ai token to solana.tokenlist.json

- src/tokens/solana.tokenlist.json
Token Address: ERPueLaiBW48uBhqX1CvCYBv2ApHN6ZFuME1MeQGTdAi
Token Name: Muskimum Impact Token
Token Symbol: MIT
Logo: https://raw.githubusercontent.com/muskimum/muskimum.github.io/main/docs/logo_light.png
Link to the official homepage of token: https://muskimum.win
Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): no atm
> update solana.tokenlist.json MIT token additional data

- src/tokens/solana.tokenlist.json
* Token Address: 5v6tZ1SiAi7G8Qg4rBF1ZdAn4cn6aeQtefewMr1NLy61
* Token Name: Solanax
* Token Symbol: SOLD
* Logo: https://solanax.org/images/icon.png
* Link to the official homepage of token: https://solanax.org
> Add Solanax [SOLD] token

- src/tokens/solana.tokenlist.json
A total of 6 new tokens have been added to the list:
1. renBTC
2. renBCH
3. renDGB
4. renDOGE
5. renLUNA
6. renZEC
All the required information has been provided for the above tokens.
> Add ren tokens to token list

- src/tokens/solana.tokenlist.json
* Token Address: AhRozpV8CDLJ5z9k8CJWF4P12MVvxdnnU2y2qUhUuNS5
* Token Name: Sol.Ark
* Token Symbol: ARK
* Logo: https://i.ibb.co/JyJ9kf0/Logo-1.png
* Link to the official homepage of token: https://www.solark.xyz/
> Updated with Sol.Ark Token

- src/tokens/solana.tokenlist.json
* Token Address: ss26ybWnrhSYbGBjDT9bEwRiyAVUgiKCbgAfFkksj4R
* Token Name: POH
* Token Symbol: SS2
* Logo:https://www.sol-talk.com/logo192.png
* Link to the official homepage of token: https://www.sol-talk.com/sol-survivor
> Add POH NFT

- src/tokens/solana.tokenlist.json
* Token Address: 6dGR9kAt499jzsojDHCvDArKxpTarNbhdSkiS7jeMAib
* Token Name: AKIHIGE Token
* Token Symbol: AKI
* Logo: https://cdn.jsdelivr.net/gh/josh-a81/AKI/AKItokenlogo.jpg
> Add AKI Token

- src/tokens/solana.tokenlist.json
* Token Address: Gro98oTmXxCVX8HKr3q2tMnP5ztoC77q6KehFDnAB983
* Token Name: SolMoon
* Token Symbol: SOLMO
* Logo: https://i.ibb.co/MSMcv41/Sol-Moon-logo.png
* Link to the official homepage of token: https://www.solmoon.co
> Add SolMoon to token list

- src/tokens/solana.tokenlist.json
> Sanddollarclassic

- src/tokens/solana.tokenlist.json
* Token Address: 3aEb4KJTWxaqKBXADw5qkAjG9K1AoLhR4CrDH6HCpGCo
* Token Name: Solana Monkey Business
* Token Symbol: SMB
* Logo : https://cdn.jsdelivr.net/gh/SolanaMonkeyBusiness/smbproject/token/SMB.png 
* Link to the official homepage of token: https://solanamonkey.business/
> Add SolanaMonkeyBusiness (SMB) token

- src/tokens/solana.tokenlist.json
* Token Address: 4TGxgCSJQx2GQk9oHZ8dC5m3JNXTYZHjXumKAW3vLnNx
* Token Name:  Oxbull Sol
* Token Symbol: OXS
* Logo: https://www.oxbull.tech/assets/icon/favicon.png
* Link to the official homepage of token: https://www.oxbull.tech/#/home
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): oxbull-tech
> Add Oxbull Sol

- src/tokens/solana.tokenlist.json
* Token Address: EdAhkbj5nF9sRM7XN7ewuW8C9XEUMs8P7cnoQ57SYE96
* Token Name: FABRIC
* Token Symbol: FAB
* Logo: https://fsynth.io/favicon-32x32.png
* Link to the official homepage of token: https://fsynth.io/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): N/A
> Add FAB token

- src/tokens/solana.tokenlist.json
* Token Address: 6G7X1B2f9F7KWcHxS66mn3ax6VPE2UMZud44RX3BzfVo
* Token Name:  Behzat  coin
* Token Symbol: BEHZAT
* Logo:  https://cdn.jsdelivr.net/gh/Tunay221/behzattoken/behzatc.png
* Link to the official homepage of token: https://twitter.com/BehzatToken
> Add Behzat to token list

- src/tokens/solana.tokenlist.json
Potato info added
- [ ✓] I will not ping the Discord about this pull request.
* Token Address: GEYrotdkRitGUK5UMv3aMttEhVAZLhRJMcG82zKYsaWB
* Token Name: POTATO
* Token Symbol: POTATO
* Logo: https://raw.githubusercontent.com/potatocoinspl/potatoArt/main/Image/logocircle.png
* Link to the official homepage of token: https://potatocoinspl.com/
> Add Potato

- src/tokens/solana.tokenlist.json
add spiderswap tokenlist
* Token Address: ATxXyewb1cXThrQFmwHUy4dtPTErfsuqkg7JcUXgLgqo
* Token Name:SpiderSwap
* Token Symbol: SPW
* Logo
> add spiderswap tokenlist

- src/tokens/solana.tokenlist.json
* Token Address: FciGvHj9FjgSGgCBF1b9HY814FM9D28NijDd5SJrKvPo
* Token Name: Twirl Governance Token
* Token Symbol: TGT
* Logo: https://i.imgur.com/eh24tVm.jpeg
* Link to the official homepage of token: https://twirlfinance.com
> Add TGT Token

- src/tokens/solana.tokenlist.json
* Token Address: A9EEvcRcT7Q9XAa6NfqrqJChoc4XGDhd2mtc4xfniQkS
* Token Name: Bilby Finance
* Token Symbol: BILBY
* Logo: https://i.ibb.co/2yqS0z8/Bilby.png
* Link to the official homepage of token: https://bilby.finance/
> Add BILBY Token

- src/tokens/solana.tokenlist.json
* Token Address: 8NGgmXzBzhsXz46pTC3ioSBxeE3w2EXpc741N3EQ8E6r
* Token Name: JOKESMEMES
* Token Symbol: JOKE
* Logo : https://jokesmemes.finance/joketoken.png
* Link to the official homepage of token: https://jokesmemes.finance/
> Add JOKESMEMES to token list

- src/tokens/solana.tokenlist.json
SOL-CATS Is First Meme + NFT token Built on Solana Blockchain. #MEOW
* Token Address: HAgX1HSfok8DohiNCS54FnC2UJkDSrRVnT38W3iWFwc8
* Token Name: SOL-CATS
* Token Symbol: MEOW
* Logo : https://raw.githubusercontent.com/SOLCATS/SOLCATS/main/solcats%20logo.jpg
* Link to the official homepage of token: solcats.xyz
> ADD $MEOW TOKEN

- src/tokens/solana.tokenlist.json
* Token Address:  GACHAfpmbpk4FLfZcGkT2NUmaEqMygssAknhqnn8DVHP
* Token Name: Gachapon
* Token Symbol: GACHA
* Logo: https://r5qzzgtjsn53w4u2wlpvrtkgstrvzpqak2i2hk7s356q4otl7p5q.arweave.net/j2GcmmmTe7tymrLfWM1GlONcvgBWkaOr8t99Djpr-_s
* Link to the official homepage of token: https://twitter.com/GACHAPON7777
> Add Gachapon token to list

- src/tokens/solana.tokenlist.json
* Token Address: rz251Qbsa27sL8Y1H7h4qu71j6Q7ukNmskg5ZDhPCg3
* Token Name: Hiro LaunchDAO
* Token Symbol: HIRO
* Logo: https://hiro-finance.github.io/assets/logo_small.png
* Link to the official homepage of token: https://hiro-finance.github.io/
> Add Hiro LaunchDAO (HIRO) token

- src/tokens/solana.tokenlist.json
Adding Plutonium (in-game currency for Plutonians game)
Thank you!
> Plutonium for Plutonians

- src/tokens/solana.tokenlist.json
Add Gangs of Solana Token
* Token Address: HcJCPYck2UsTMgiPfjn6CS1wrC5iBXtuqPSjt8Qy8Sou
* Token Name: Gangs of Solana
* Token Symbol: GANGS
* Logo: https://raw.githubusercontent.com/gangsofsolana/main/main/gangsofsolana.svg
* Link to the official homepage of token: https://gangsofsolana.com/
> Add Gangs of Solana Token

- src/tokens/solana.tokenlist.json
add solster token
{
"chainId": 101,
"address": "9zoqdwEBKWEi9G5Ze8BSkdmppxGgVv1Kw4LuigDiNr9m",
"symbol": "STR",
"name": "Solster",
"decimals": 9,
"logoURI": "https://solster.finance/logo-mark.png",
"tags": [],
"extensions": {
"website": "https://solster.finance",
"twitter": "https://twitter.com/solster_finance"
}
}
* Token Name: 
* Logo
> add solster str token

- src/tokens/solana.tokenlist.json
* Token Address: GReBHpMgCadZRij4B111c94cqU9TktvJ45rWZRQ5b1A5
* Token Name: Penguincoin
* Token Symbol: PINGU
* Logo: https://www.seekpng.com/png/full/612-6121902_pingu-the-penguin-pingu-cartoon.png
* Link to the official homepage of token: https://twitter.com/penguincoin1
> Add Penguincoin

- src/tokens/solana.tokenlist.json
Token Address: EGN2774kzKyUnJs2Gv5poK6ymiMVkdyCQD2gGnJ84sDk
Token Name: Neftea Labs Coin
Token Symbol: NEFT
Logo: https://gateway.pinata.cloud/ipfs/QmdcmEVy9dyBdLoHSTfjUwQxmVLJPH157WmVGd74JF6obX
Link to the official homepage of token: https://www.neftealabs.com/
> Neftea Labs token request

- src/tokens/solana.tokenlist.json
* Token Address: qs9Scx8YwNXS6zHYPCnDnyHQcRHg3QwXxpyCXs5tdM8
* Token Name: POWER COIN
* Token Symbol: POCO
* Logo https://cdn.jsdelivr.net/gh/powercoinpoco/powercoinpoco/poco.jpg
* Link to the official homepage of token: https://powercoinpoco.medium.com/
> Add $POCO Token

- src/tokens/solana.tokenlist.json
* Token Address: D3gHoiYT4RY5VSndne1fEnpM3kCNAyBhkp5xjNUqqPj9
* Token Name: ProExis Prova de Existência Blockchain
* Token Symbol: D3gHoiYT4RY5VSndne1fEnpM3kCNAyBhkp5xjNUqqPj9
* Logo https://raw.githubusercontent.com/provadeexistencia/img/main/logo_proexis.jpg
* Link to the official homepage of token: https://provadeexistencia.com.br
> Add PROEXIS token

- src/tokens/solana.tokenlist.json
* Token Address: Bx1fDtvTN6NvE4kjdPHQXtmGSg582bZx9fGy4DQNMmAT
* Token Name: Solcubator
* Token Symbol: SOLC
* Logo: http://solcubator.io/logo.png
* Link to the official homepage of token: http://solcubator.io
> added SOLC token

- src/tokens/solana.tokenlist.json
* Token Address: 72fFy4SNGcHoEC1TTFTUkxNHriJqg3hBPsa2jSr2cZgb
* Token Name: BlizeX
* Token Symbol: BZX
* Logo: https://raw.githubusercontent.com/Blizex-Official/blizex-token/main/logo.jpg
* Link to the official homepage of token: https://www.blizex.co
> Add BZX Token

- src/tokens/solana.tokenlist.json
* Token Address: 5KV2W2XPdSo97wQWcuAVi6G4PaCoieg4Lhhi61PAMaMJ
* Token Name: GÜ
* Token Symbol: GÜ
* Logo: https://cdn.jsdelivr.net/gh/Seigneur-Machiavel/kugle.github.io/Tokens/Logo_GU_512.png
* Link to the official homepage of token: https://kugle.org (work in progress)
*Twitter: https://twitter.com/Kugle_
> add GÜ token

- src/tokens/solana.tokenlist.json
I will not ping the Discord about this pull request.
Please provide the following information for your token.
Token Address: 97qAF7ZKEdPdQaUkhASGA59Jpa2Wi7QqVmnFdEuPqEDc
Token Name: DIAMOND
Token Symbol: LOVE
Logo: https://raw.githubusercontent.com/AdamBraham88/SPL-TOKEN/main/Diamond-Love-icon.png
Link to the official homepage of token: https://diamondlove.io/
Telegram: https://t.me/DiamondLoveX
> UPDATE DIAMOND LOVE TOKEN

- src/tokens/solana.tokenlist.json
* Token Address: DK64rmGSZupv1dLYn57e3pUVgs9jL9EKLXDVZZPsMDz8
* Token Name: ArtBomb
* Token Symbol: ARTBOMB
* Logo https://gateway.pinata.cloud/ipfs/QmNdspog9ngoEdkDiavTZr84N4KLmqN3PN15FK6FDVqcN7
* Link to the official homepage of token: artbomb.xyz
> Add ARTBOMB Token

- src/tokens/solana.tokenlist.json
* Token Address: AnyCsr1VCBZcwVAxbKPuHhKDP5DQQSnRxGAo4ycgRMi2
* Token Name: Dalmatiancoin
* Token Symbol: DAL
* Logo: https://res.cloudinary.com/dtbjhs8a6/image/upload/v1622836689/t55xirsxagaanntdt50i.jpg
* Link to the official homepage of token: https://dalmatiancoin.org/
> Add Dalmatiancoin Token

- src/tokens/solana.tokenlist.json
* Token Address: HiL1j5VMR9XtRnCA4mxaVoXr6PMHpbh8wUgfPsAP4CNF
* Token Name: SolNHD
* Token Symbol: SolNHD
* Logo: https://raw.githubusercontent.com/duynguyen93/SolNHD/main/images/logo.png
* Link to the official homepage of token: https://solnhd.com
> Add New SolNHD Token

- src/tokens/solana.tokenlist.json
Token Address: Amt5wUJREJQC5pX7Z48YSK812xmu4j3sQVupNhtsEuY8
Token Name: FROG
Token Symbol: FROG
Logo: https://froglana.com/images/rsz_froglogom8.png
Link to the official homepage of token: https://www.froglana.com/
Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): TBD
> Replace frog logo

- src/tokens/solana.tokenlist.json
Hello @oJshua , here is a minor update, thanks in advance for your prompt feedback.
Update our SolanaSail Official Twitter name, same name than our Website.
https://twitter.com/SolanaSail
> Update SAIL Twitter account 

- src/tokens/solana.tokenlist.json
added blades token (fixed)
* Token Address: DrcPRJPBiakQcWqon3gZms7sviAqdQS5zS5wvaG5v6wu
* Token Name: BladesToken
* Token Symbol: BLD
* Logo: https://i.imgur.com/MfxQycw.jpeg
* Link to the official homepage of token: https://blades.finance/
> added blades token (fixed)

- src/tokens/solana.tokenlist.json
> add qwikpay.io QWK token

- src/tokens/solana.tokenlist.json
Token Address: BTyJg5zMbaN2KMfn7LsKhpUsV675aCUSUMrgB1YGxBBP
Token Name: Gooseberry
Token Symbol: GOOSEBERRY
Logo : https://gooseberry.changr.ca/gooseberry.png
Link to the official homepage of token: https://gooseberry.changr.ca
> Add GOOSEBERRY token

- src/tokens/solana.tokenlist.json
* Token Address: GpYMp8eP3HADY8x1jLVfFVBVYqxFNxT5mFhZAZt9Poco
* Token Name: Crazy Ape Coin
* Token Symbol: CAPE
* Logo https://i.ibb.co/bPR09V9/cape-500x500.png
* Link to the official homepage of token: https://www.crazyapecoin.com
> Add CAPE token

- src/tokens/solana.tokenlist.json
Please provide the following information for your token.
Please include change to the src/tokens/solana.tokenlist.json file in the PR
Token Address: DubwWZNWiNGMMeeQHPnMATNj77YZPZSAz2WVR5WjLJqz
Token Name: CropperFinance
Token Symbol: CRP
Logo : https://pbs.twimg.com/profile_images/1399749127089627139/UHqlWRaL_400x400.jpg
Link to the official homepage of token: https://cropper.finance/
> Add CropperFinance Token $CRP

- src/tokens/solana.tokenlist.json
* Token Address: ER8Xa8YxJLC3CFJgdAxJs46Rdhb7B3MjgbPZsVg1aAFV
* Token Name: MOLAMON
* Token Symbol: MOLAMON
* Logo: https://i.ibb.co/cNhCc33/molamon.jpg
* Link to the official homepage of token: https://www.moonlana.com/
> update $MOLAMON imageUrl

- src/tokens/solana.tokenlist.json
* Token Address: B3Ggjjj3QargPkFTAJiR6BaD8CWKFUaWRXGcDQ1nyeeD
* Token Name: PARTI
* Token Symbol: PARTI
* Logo: https://raw.githubusercontent.com/partifinance/particle-brand/main/particle-finance-logo.png
* Link to the official homepage of token: https://parti.finance
> Add Particle Finance token

- src/tokens/solana.tokenlist.json
* Token Address: 5igDhdTnXif5E5djBpRt4wUKo5gtf7VicHi8r5ada4Hj
* Token Name: NIA
* Token Symbol: NIALABS
* Logo: https://i.ibb.co/z6DHkSH/nia-logo.png
* Link to the official homepage of token: https://www.nialabs.com/
> add token NIA

- src/tokens/solana.tokenlist.json
Add Corvus Token to token-list.
* Token Address: GQnN5M1M6oTjsziAwcRYd1P7pRBBQKURj5QeAjN1npnE
* Token Name: Project Corvus
* Token Symbol: CORV
* Logo: http://dixon.company/corvus.png
* Link to the official homepage of token: https://dixon.company
> Pls Add Project Corvus to token-list

- src/tokens/solana.tokenlist.json
> Add HLTH token

- src/tokens/solana.tokenlist.json
Token Address: Fx14roJm9m27zngJQwmt81npHvPc5pmF772nxDhNnsh5
Token Name: Raydium LP Token (LIQ-USDC)
Token Symbol: LIQ-USDC
Logo: https://cdn.jsdelivr.net/gh/solana-labs/token-list@main/assets/mainnet/RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr/logo.png
Link to the official homepage of token: https://raydium.io/ (refers to https://liqsolana.com/ for detail)
> Add LIQ Raydium LP Token to Token list

- src/tokens/solana.tokenlist.json
Updating URL from https://www.klbtoken.com to https://klbtoken.com and added Market Id.
> Update URL & Add Market Id

- src/tokens/solana.tokenlist.json
Just updating SKEM and AUSS to include their Market Ids.
> Add AUSS and SKEM Market Ids

- src/tokens/solana.tokenlist.json
Updated to Permissionless
Token Address: Fx14roJm9m27zngJQwmt81npHvPc5pmF772nxDhNnsh5
Token Name: Raydium Permissionless LP Token (LIQ-USDC)
Token Symbol: LIQ-USDC
Logo: https://cdn.jsdelivr.net/gh/solana-labs/token-list@main/assets/mainnet/RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr/logo.png
Link to the official homepage of token: https://raydium.io/ (refers to https://liqsolana.com/ for detail)
> Update Permissionless LP Token

- src/tokens/solana.tokenlist.json
* Token Address: DK64rmGSZupv1dLYn57e3pUVgs9jL9EKLXDVZZPsMDz8
* Token Name: ABOMB
* Token Symbol: ArtBomb
* Logo. https://gateway.pinata.cloud/ipfs/QmNdspog9ngoEdkDiavTZr84N4KLmqN3PN15FK6FDVqcN7
* Link to the official homepage of token: artbomb.xyz
> update artbomb token logo

- src/tokens/solana.tokenlist.json
Reverts solana-labs/token-list#410
> Revert "Update Permissionless LP Token"

- CHANGELOG.md
- package.json
- src/tokens/solana.tokenlist.json
> LIQ Protocol - Updated name of the file

- src/tokens/solana.tokenlist.json
> Changed logo link

- src/tokens/solana.tokenlist.json
* Token Address: FgX1WD9WzMU3yLwXaFSarPfkgzjLb2DZCqmkx9ExpuvJ
* Token Name: NINJA
* Token Symbol: NINJA
* Logo: https://raw.githubusercontent.com/ninjaprotocolsol/ninjaprotocol/main/newninja-token.png
* Link to the official homepage of token: https://www.ninjaprotocol.io/
> Added New Ninja Token & Replaced Name and Symbol for older one

- src/tokens/solana.tokenlist.json
* Token Address: **SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr**
* Token Name: **Solrise Finance**
* Token Symbol: **SLRS**
* Logo: https://i.ibb.co/tqbTKTT/slrs-256.png
* Link to the official homepage of token: https://solrise.finance
* Coingecko ID: **solrise-finance**
* Twitter: https://twitter.com/SolriseFinance
* Telegram: https://t.me/solrisefinance
* Medium: https://blog.solrise.finance
* Discord: https://discord.gg/xNbGgMUJfU
> Add Solrise Finance (SLRS) token

- src/tokens/solana.tokenlist.json
* Token Address: ss1gxEUiufJyumsXfGbEwFe6maraPmc53fqbnjbum15
* Token Name: Naked Shorts
* Token Symbol: SS1
* Logo: https://www.sol-talk.com/logo192.png
* Link to the official homepage of token:https://www.sol-talk.com/sol-survivor
> Update Naked Shorts NFT information

- src/tokens/solana.tokenlist.json
Update Solape Logo
- [ x] I will not ping the Discord about this pull request.
* Token Name: 
* Logo
> Update Solape Logo

- src/tokens/solana.tokenlist.json
* Token Address: CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5
* Token Name: Ren Bitcoin
* Token Symbol: renBTC
* Logo: https://cdn.jsdelivr.net/gh/trustwallet/assets@master/blockchains/ethereum/assets/0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D/logo.png
* Link to the official homepage of token: https://renproject.io/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): renbtc
> Add renBTC

- src/tokens/solana.tokenlist.json
Added an extension for the Kekwcoin.
> added usdc market

- src/tokens/solana.tokenlist.json
* Token Address: E5rk3nmgLUuKUiS94gg4bpWwWwyjCMtddsAXkTFLtHEy
* Token Name: Wootrade Network
* Token Symbol: WOO
* Logo
* Link to the official homepage of token: https://woo.network
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): wootrade-network
> Add WOO token

- src/tokens/solana.tokenlist.json
Added Medium, Discord and description information to the Kekwcoin token
> Added Medium, Discord and description information

- src/tokens/solana.tokenlist.json
> Updated LIQ-SOL LP Token

- src/tokens/solana.tokenlist.json
This is the LP token for the USDC-USDT-PAI pool for Mercurial: https://mercurial.finance/
> Mercurial LP Token (USDC-USDT-PAI)

- src/tokens/solana.tokenlist.json
* Token Address: ss26ybWnrhSYbGBjDT9bEwRiyAVUgiKCbgAfFkksj4R
* Token Name: POH
* Token Symbol: SS2
* Logo: https://www.sol-talk.com/logo192.png
* Link to the official homepage of token: https://www.sol-talk.com/sol-survivor
> Update POH NFT

- src/tokens/solana.tokenlist.json
> Re Adding Trollbox token to token-list json

- src/tokens/solana.tokenlist.json
SODA:
* Token Address: sodaNXUbtjMvHe9c5Uw7o7VAcVpXPHAvtaRaiPVJQuE
* Token Name: cheesesoda token
* Token Symbol: SODA
* Logo: https://raw.githubusercontent.com/cheesesoda/soda-tokens/main/soda.svg
* Link to the official homepage of token: https://token.cheesesoda.com
SODAO:
* Token Address: sodaoT6Wh1nxHaarw4kDh7AkK4oZnERK1QgDUtHPR3H
* Token Name: cheesesodaDAO
* Token Symbol: SODAO
* Logo: https://raw.githubusercontent.com/cheesesoda/soda-tokens/main/sodao.svg
* Link to the official homepage of token: https://dao.cheesesoda.com
* Coingecko ID if …
> Add SODA and SODAO tokens

- src/tokens/solana.tokenlist.json
Please provide the following information for your token.
Token Address: A2T2jDe2bxyEHkKtS8AtrTRmJ9VZRwyY8Kr7oQ8xNyfb
Token Name: Space Hamster
Token Symbol: HAMS
Logo: https://i.ibb.co/2cpC3nb/HAMS.png
Link to the official homepage of token: https://www.solhamster.space/
> Updating HAMS token

- src/tokens/solana.tokenlist.json
* Token Address: 9eaAUFp7S38DKXxbjwzEG8oq1H1AipPkUuieUkVJ9krt
* Token Name: KDC (KURZ Digital Currency)
* Token Symbol: KDC
* Logo: https://kurzdigital.com/images/KDC_logo.png
* Link to the official homepage of token: https://www.kurzdigital.com
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): None
> Add KDC token

- src/tokens/solana.tokenlist.json
I'm an idiot, and I listed the SODA market Id under SODAO. This is resolved with this PR.
> Correct Serum Market from SODAO to SODA

- src/tokens/solana.tokenlist.json
- [ X] I will not ping on Discord/Twitter/email about this pull request.
PRs are reviewed in bulk and and can take up to two weeks to be merged.
-> Changing decimal of GÜ from 6 to 9.
-> (Logo-link changed before)
* Token Address: 5KV2W2XPdSo97wQWcuAVi6G4PaCoieg4Lhhi61PAMaMJ
* Token Name: GÜ
* Token Symbol: GÜ
* Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5KV2W2XPdSo97wQWcuAVi6G4PaCoieg4Lhhi61PAMaMJ/logo.png
* Link to the official homepage of token: https://kugle.org
*Twitter: https://twitter.com/Kugle_
* Coingecko ID if available …
> Update tokenlist : GÜ decimal fix

- src/tokens/solana.tokenlist.json
* Token Name: **Solrise Finance**
* Token Symbol: **SLRS**
Added entry:
* Serum V3 USDC market: **2Gx3UfV831BAh8uQv1FKSPKS9yajfeeD8GJ4ZNb2o2YP**
> Add SLRS/UDSC market to SLRS token

- src/tokens/solana.tokenlist.json
* Token Address: 3iXydLpqi38CeGDuLFF1WRbPrrkNbUsgVf98cNSg6NaA
*Token Name: SprokenToken
*Token Symbol: Spro
*Logo: https://cdn.jsdelivr.net/gh/kechricc/Sproken-Token-Logo/SprokenToken.png
*Link to the official homepage of token: https://www.sprokentoken.com
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): Not available yet
> Added SprokenToken

- src/tokens/solana.tokenlist.json
- [ x] I will not ping the Discord about this pull request.
* Token Name: 
* Logo
> Update solana.tokenlist.json add GQO

- .github/workflows/build.yml
Remove mergepal running on main.
> Remove mergepal on Main branch

- .github/workflows/build.yml
Fix `build.yml` token discovery issues.
> Fix target payload

- .github/workflows/automerge.yml
Attempt to integrate automerge (dry run).
> feat: attempt automerge

- .github/workflows/automerge.yml
Remove dry run on Automerge, fix version.
> Fix automerge version

- .github/workflows/automerge.yml
Remove dryrun field from Automerge action.
> Remove dryrun

- src/tokens/solana.tokenlist.json
> Entry for Only1 (LIKE) token

- src/tokens/solana.tokenlist.json
> Change address for GQO token

- src/tokens/solana.tokenlist.json
PRs are reviewed in bulk and and can take up to two weeks to be merged.
> Add Raydium LP Token

- src/tokens/solana.tokenlist.json
PRs are reviewed in bulk and and can take up to two weeks to be merged.
* Token Name: 
> Dinarius listing name

- CHANGELOG.md
- package.json
- src/tokens/solana.tokenlist.json
> Repair Logo, Add Market, and also Description

- src/tokens/solana.tokenlist.json
* Token Address: FqJE1neoCJrRwxfC9mRL6FduuZ1gCX2FUbya5hi8EQgA
* Token Name: Viloid Coin
* Token Symbol: VLDC
* Logo: https://cdn.jsdelivr.net/gh/viloidcoin/logo/vldc.png
* Website: https://viloidcoin.com
* Github: https://github.com/viloidcoin
> Add VLDC Token

- src/tokens/solana.tokenlist.json
----
* Token Name: 
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): "bole-token"
> Add BOLE market and CoingeckoId

- src/tokens/solana.tokenlist.json
a small fix for dcash logo url
> fix dcash logo url

- src/tokens/solana.tokenlist.json
----
* Token Address: AMdnw9H5DFtQwZowVFr4kUgSXJzLokKSinvgGiUoLSps
* Token Name: Moonlana
* Token Symbol: MOLA
* Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/AMdnw9H5DFtQwZowVFr4kUgSXJzLokKSinvgGiUoLSps/logo.png
* Link to the official homepage of token: https://www.moonlana.com/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): moonlana
> Add coingeckoId to Moonlana Token

- src/tokens/solana.tokenlist.json
> Change LARIX symbol

- src/tokens/solana.tokenlist.json
> Add APEX Coingecko ID

- src/tokens/solana.tokenlist.json
Update new LP tokens and rename legacy.
> Update Raydium LP tokens

- src/tokens/solana.tokenlist.json
> Add Coingecko ID to SBR

- src/tokens/solana.tokenlist.json
> Add STEP for devnet

- src/tokens/solana.tokenlist.json
> Remove SMB token

- src/tokens/solana.tokenlist.json
----
* Token Address: 5KV2W2XPdSo97wQWcuAVi6G4PaCoieg4Lhhi61PAMaMJ
* Token Name: GÜ
* Token Symbol: GÜ
* Link to the official homepage of token: https://kugle.org/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): gu
> Add GÜ CoinGecko ID

- src/tokens/solana.tokenlist.json
Updated coingecko ID for FABRIC
> Added Coingecko ID to FABRIC

- src/tokens/solana.tokenlist.json
Added Coingecko ID to DEXLAB
Added serumV3Usdc
Added Twitter url
> Added Coingecko ID to DEXLAB

- src/tokens/solana.tokenlist.json
> Add LIQ - USDC Orca LP Token

- src/tokens/solana.tokenlist.json
**Changes**
Updating ORCA token extensions to include the following fields
- `coingeckoId`
- `telegram`
- `discord`
- `serumV3Usdc`
> Update ORCA token extensions

- src/tokens/solana.tokenlist.json
Add CYS/USDC market
----
* Token Name: 
> Add Serum market and Coingecko ID for Cyclos (CYS)

- src/tokens/solana.tokenlist.json
> added droid finance

- assets/mainnet/2XkWD6spByDUoR3VDEjPXz4kxFV8e1skwaRSBArRLG3a
> droidfinance

- src/tokens/solana.tokenlist.json
Added $CATO coingecko id, Updated website link
----
* Token Name: 
> Added $CATO coingecko id, Updated website link

- src/tokens/solana.tokenlist.json
> Remove www subdomain from website url

- src/tokens/solana.tokenlist.json
This token's purpose is for food reviewing and at the same time educational purpose to teach how to create a token on Solana
----
* Token Name: 
* Link to the official homepage of token: 
> Add YUMZ token

- src/tokens/solana.tokenlist.json
* Token Address: 95KN8q3qubEVjPf9trgyur2nHx8T5RCmztRbLuQ5E5i
* Token Name: Solminter
* Token Symbol: SMRT
* Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/95KN8q3qubEVjPf9trgyur2nHx8T5RCmztRbLuQ5E5i/logo.png
* Link to the official homepage of token: [https://solminter.com](https://solminter.com)
* Coingecko ID if available): solminter
> Add solminter to token list

- src/tokens/solana.tokenlist.json
> Corestarter Token Added

- src/tokens/solana.tokenlist.json
> Added PORT Serum V3 market and Coingecko ID.

- src/tokens/solana.tokenlist.json
changed url of Refrak
----
* Token Name: 
> changed url of Refrak

- src/tokens/solana.tokenlist.json
> Add Token for SPL mainnet

- src/tokens/solana.tokenlist.json
> Created token COD

- src/tokens/solana.tokenlist.json
> Add `Coingecko ID` for Only1 (LIKE)

- src/tokens/solana.tokenlist.json
> Twitter Change Behzat Token

- src/tokens/solana.tokenlist.json
> ADD XTAG TOKEN

- src/tokens/solana.tokenlist.json
> Update the logos of Scallop token

- src/tokens/solana.tokenlist.json
updated grape logo, properly centered in wallet
> Grape logo update

- src/tokens/solana.tokenlist.json
> add SNS token

- src/tokens/solana.tokenlist.json
> Please add Kism to tokenlist

- assets/mainnet/7kpzQByqsfmZSX5Y71YtncBvuhFVFJBLUvJKqqNMfT8P/logo.svg
- src/tokens/solana.tokenlist.json
----
* Token Address: 7kpzQByqsfmZSX5Y71YtncBvuhFVFJBLUvJKqqNMfT8P
* Token Name: TaskDapp
* Token Symbol: TSK
* Logo: 7kpzQByqsfmZSX5Y71YtncBvuhFVFJBLUvJKqqNMfT8P/token.svg
* Link to the official homepage of token: taskdapp.io
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): NA
> TaskDapp token Added

- src/tokens/solana.tokenlist.json
> Update LIQ LP token information Solana tokenlist 

- src/tokens/solana.tokenlist.json
----
* Token Address: 6foyeENL9GhqZEqPeaRK9YtP8HnFfej1JBwdn5rcsPDi
* Token Name: iMentusCoin
* Token Symbol: iM
* Link to the official homepage of token: 
> add iMentusCoin

- src/tokens/solana.tokenlist.json
> added serumv3usdc for hotto HottoShotto

- src/tokens/solana.tokenlist.json
> Add USDT_ILT into Token List

- assets/mainnet/5KB7WK1sB7WpoFXAiKoyhWCh44jHfTMtXDuvaSRQ4TR1/logo.svg
- src/tokens/solana.tokenlist.json
> Add GIG token

- src/tokens/solana.tokenlist.json
> Change to the `src/tokens/solana.tokenlist.json` file - add pepe token

- src/tokens/solana.tokenlist.json
> New token solana.tokenlist.json

- src/tokens/solana.tokenlist.json
----
* Token Address: E28mvmaJa9LHLpJWiWsLd4eERL7w9j6uGAUwBWpH5UFd
* Token Name: SolBull
* Token Symbol: SBULL
* Logo: https://cdn.jsdelivr.net/gh/kasshen/SolBull/SolBull_Logo.png
* Link to the official homepage of token: https://twitter.com/SolBull1
> Add SolBull (SBULL) Token

- assets/mainnet/FiCiuX9DetEE89PgRAU1hmoptnem8b1fkpEq8PGYTYkd/logo.svg
- src/tokens/solana.tokenlist.json
----
* Token Address: FiCiuX9DetEE89PgRAU1hmoptnem8b1fkpEq8PGYTYkd
* Token Name: Million
* Token Symbol: MM
* Logo: In the commit
* Link to the official homepage of token: https://www.milliontoken.org/
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): million
> Add Million Token (MM)

- src/tokens/solana.tokenlist.json
----
* Token Address: 8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA
* Token Name: GRAPE
* Token Symbol: GRAPE
> Add Grape coingeckoid

- src/tokens/solana.tokenlist.json
----
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): cheesesoda-token
> Add SODA CoinGecko listing

- src/tokens/solana.tokenlist.json
> Update data coingecko C98

- src/tokens/solana.tokenlist.json
Deleted Telegram channel as it is not used anymore
Added Serum market
Added Coingecko ID
----
* Token Name: 
> Updated CHEEMS token's extensions

- src/tokens/solana.tokenlist.json
> Update AGTE token info

- src/tokens/solana.tokenlist.json
> add waterfall bot link for Saber, PORT, C98, SUNNY, ATLAS, POLIS

- src/tokens/solana.tokenlist.json
----
* Token Address: yes
* Token Name: yes
* Token Symbol: yes
* Logo: (logo should be uploaded under assets/mainnet/<mint address>/*.<png/svg>) - yes
* Link to the official homepage of token:yes
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): no
> Add SolFarm Collateral Tokens

- src/tokens/solana.tokenlist.json
> Add Swordian Token

- src/tokens/solana.tokenlist.json
----
* Token Address: iVNcrNE9BRZBC9Aqf753iZiZfbszeAVUoikgT9yvr2a
* Token Name: Investin
* Token Symbol: IVN
* Link to the official homepage of token: https://www.investin.pro/ 
> token logo updated

- assets/mainnet/SioTkQxHyAs98ouRiyi1YDv3gLMSrX3eNBg61GH7NrM/logo.svg
- src/tokens/solana.tokenlist.json
----
* Token Address: SioTkQxHyAs98ouRiyi1YDv3gLMSrX3eNBg61GH7NrM
* Token Name: Simplio
* Token Symbol: Sio
* Logo: (logo should be uploaded under assets/mainnet/<mint address>/*.<png/svg>) it is in svg format
* Link to the official homepage of token: https://simplio.io/ (Site is almost ready. We prepare to launch in max 2 weeks)
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): This we will provide later with another PR as we are not listed yet on …
> Add SIO (Simplio)

- src/tokens/solana.tokenlist.json
> Add Solana Yield

- src/tokens/solana.tokenlist.json
----
* Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): black-label
> Add coingeckoId to KLB listing.

- src/tokens/solana.tokenlist.json
> Add Solana Yield with New logo

- src/tokens/solana.tokenlist.json
----
* Token Address: 6xtyNYX6Rf4Kp3629X11m1jqUmkV89mf9xQakUtUQfHq
* Token Name: CHIHUAHUA
* Token Symbol: CHIH
* Logo: https://raw.githubusercontent.com/ChihuahuaSol/Chihuahua/main/chihuahua-token.png
* Link to the official homepage of token: https://chihuahuasol.com/
> Add CHIH Token

- src/tokens/solana.tokenlist.json
> update crystal token

- src/tokens/solana.tokenlist.json
> FTT token added

- src/tokens/solana.tokenlist.json
> Adding BRANE TOKEN to solana.tokenlist.json

- src/tokens/solana.tokenlist.json
----
* Token Address: 4R8DBzZEzjBQzPJe4qqaxXM97am7unGM1ZYfviS6oSFe
* Token Name: ANUBEAST
* Token Symbol: ANU
> Add ANUBEAST

- src/tokens/solana.tokenlist.json
> add info for Naxar

- src/tokens/solana.tokenlist.json
> Added CoinGecko to Allbridge

- src/tokens/solana.tokenlist.json
> Add soltomm

- assets/mainnet/soso1vCmdxwEZqU47M4NZ4MxZH19ppgqF1auG7dP3wz/logo.svg
- src/tokens/solana.tokenlist.json
PR for $SSL sosol - monetized, censorship resistant social media containing:
* Token Address
* Token Name
* Token Symbol
* Logo
* Links (homepage | twitter)
> Add sosol $SSL token to list

- src/tokens/solana.tokenlist.json
> added SEED coin

- src/tokens/solana.tokenlist.json
> Update SAIL & gSAIL with serumV3Usdc field

- src/tokens/solana.tokenlist.json
> first commit for my token KPLR adding Logo & Address

- src/tokens/solana.tokenlist.json
> Add SUSD Token

- src/tokens/solana.tokenlist.json
> add Lag Extensions

- src/tokens/solana.tokenlist.json
> Add ShibSol (SHIBS)

- src/tokens/solana.tokenlist.json
> add oink token

- src/tokens/solana.tokenlist.json
> adding serum market for cubecoin

- src/tokens/solana.tokenlist.json
> Created new token BNN

- src/tokens/solana.tokenlist.json
> IDENT and CERT tokens minted by IdentiCert

- src/tokens/solana.tokenlist.json
> Added Solanim (SOLM) Token Details.

- src/tokens/solana.tokenlist.json
> Update twitter and telegram for Uncle Murphy Coin

- src/tokens/solana.tokenlist.json
> Updated BAB

- src/tokens/solana.tokenlist.json
> Add Sola Ninja

- src/tokens/solana.tokenlist.json
> First commit for RBTP

- src/tokens/solana.tokenlist.json
> Add coingeckoID + serumV3Usdc for CropperFinance

- src/tokens/solana.tokenlist.json
> update Arabic Bitcoin

- src/tokens/solana.tokenlist.json
> Added Oridion

- solana.tokenlist.json
---
Token Address: 8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s
Token Name: SolDoge
Token Symbol: SDOGE
Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s/logo.png
Link to the official homepage of token: https://www.soldoge.io …
> Added coingeckoId for SDOGE.

- assets/mainnet/6JdcMdhqgCtcP4U9tieRqmKLhPLxRMLC67QfmdXAJBvZ
---
- Token Address: 6JdcMdhqgCtcP4U9tieRqmKLhPLxRMLC67QfmdXAJBvZ
- Token Name: Kitty Solana
- Token Symbol: KITTY
- Logo:  https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6JdcMdhqgCtcP4U9tieRqmKLhPLxRMLC67QfmdXAJBvZ/logo.png 
- Link to the official homepage of token: https://twitter.com/kitty_solana
> Solana Kitty

- assets/mainnet/FxW1ZZket6uqPre4biur2TxM2yjbtP8EYCotpRLxzAUK
---
- Token Address:FxW1ZZket6uqPre4biur2TxM2yjbtP8EYCotpRLxzAUK
- Token Name:The One Piece
- Token Symbol:TOP
- Link to the official homepage of token:https://www.onepice.vip/
- https://twitter.com/theonepiece01
> Add The One Piece

- src/tokens/solana.tokenlist.json
> Add Valknut Token

- src/tokens/solana.tokenlist.json
> Bark'o'Finance

- solana.tokenlist.json
> adding ligma token

- solana.tokenlist.json
> added SolShell (SSH) tw

- src/tokens/solana.tokenlist.json
> bork logo update

- src/tokens/solana.tokenlist.json
> Update Hippo Coin

- src/tokens/solana.tokenlist.json
---
- Token Address: 8ZY7EkwN7LxifYvvrQDbpjqxkrjHUFMwWgq8fupNNvub
- Token Name: daib test token
- Token Symbol: BIAD
- Logo: https://s3.us-west-2.amazonaws.com/secure.notion-static.com/02242929-14bc-4204-ac71-56d855a07078/512_daia.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20211104%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20211104T051518Z&X-Amz-Expires=86400&X-Amz-Signature=df1424dcb1be408faa45ef6af1f7769 …
> PR BIAD Token

- assets/mainnet/382HfaEjcUNhwoGbYmL58DVX8GUvjrXiTPchCWKjchWA
---
- Token Address:382HfaEjcUNhwoGbYmL58DVX8GUvjrXiTPchCWKjchWA
- Token Name:Sheeplana
- Token Symbol:SPLN
- Link to the official homepage of token:https://www.sheeplana.online
- https://twitter.com/sheeplana1
> Add Sheeplana

- src/tokens/solana.tokenlist.json
---
- Token Address: TrickCA8nD77Y6iHHEQBAaBFDjFa5zohSThmSVfz2X9
- Token Name: SolTricks token
- Token Symbol: Trick
- Logo: http://static.soltricks.io/icon.png
- Link to the official homepage of token: https://soltricks.io
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): null
> add Trick token

- src/tokens/solana.tokenlist.json
---
- Token Address: EFYKDdppK1FjixaxExpVhoTd8gtAmncbhQYruzWyG6Cx
- Token Name: Spookeletons Token
- Token Symbol: SPKL
- Link to the official homepage of token: https://www.spookeletons.com
> Adding SPKL

- src/tokens/solana.tokenlist.json
---
- Token Address:JTTez7NDqtU4ZqZJmLLXt6K9f75izfTApQqmvMCn4jU
-Token Name:Japan Travel Token
-Token Symbol:JTT
-Logo: http://www.japantravel.me/jtticon.png
-Link to the official homepage of token:https://www.japantravel.me
-Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_):null
> add JTT token

- src/tokens/solana.tokenlist.json
> Adding BRZ token

- assets/mainnet/4wfCtMp8KQ7r61V4qH2VtHxFjVjUdsWhgAmZgQi33UkT/logo.svg
- src/tokens/solana.tokenlist.json
> Adding ARDN Ariadne

- solana.tokenlist.json
> add BIP to root tokenlist

- src/tokens/solana.tokenlist.json
> Adding MEW MEWSOL

- src/tokens/solana.tokenlist.json
> Added Allbridge USDC from Celo

- src/tokens/solana.tokenlist.json
---
- Token Address: rendopHqu4oE94AXjEEtporr1xW8Fsp4bZDccyMTYzU
- Token Name: rendo.club
- Token Symbol: RENDO
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/rendopHqu4oE94AXjEEtporr1xW8Fsp4bZDccyMTYzU/logo.png
- Link to the official homepage of token: https://rendo.club
> Adding RENDO Token

- src/tokens/solana.tokenlist.json
> Add CoinGecko

- src/tokens/solana.tokenlist.json
---
- Token Address: q4bpaRKw3fJB1AJBeeBaKv3TjYzWsmntLgnSB275YUb
- Token Name: Turtles Token
- Token Symbol: TRTLS
> Adding TRTLS

- src/tokens/solana.tokenlist.json
> Add MONDOCOIN

- src/tokens/solana.tokenlist.json
---
- Token Address: FTkj421DxbS1wajE74J34BJ5a1o9ccA97PkK6mYq9hNQ
- Token Name: Synex Coin
- Token Symbol: MINECRAFT
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/FTkj421DxbS1wajE74J34BJ5a1o9ccA97PkK6mYq9hNQ/logo.png
- Link to the official homepage of token: synexcoin.dev
> first commit for MINECRAFT & Synexcoin

- src/tokens/solana.tokenlist.json
> Added Solana Donke Business Token. 

- src/tokens/solana.tokenlist.json
> Update FLOOF token-list info: add coingecko ID, add srmv3 market, update logo

- src/tokens/solana.tokenlist.json
> added solbunny

- src/tokens/solana.tokenlist.json
> Add coingecko SLND

- src/tokens/solana.tokenlist.json
> Add SHBL-USDC LP

- src/tokens/solana.tokenlist.json
* add second line address to fix empty issue
> fix: fix empty space issue

- src/tokens/solana.tokenlist.json
* fix empty space cause problem
> fix: fix empty space

- src/tokens/solana.tokenlist.json
> KAJU icon first update

- src/tokens/solana.tokenlist.json
> Add INUGAMI Coin

- src/tokens/solana.tokenlist.json
> ARDN add coingeckoId

- solana.tokenlist.json
> Solearna-Token-Added

- src/tokens/solana.tokenlist.json
> add-betaFANT-token

- solana.tokenlist.json
> Adding ICA NFTs

- src/tokens/solana.tokenlist.json
> add telegram link

- src/tokens/solana.tokenlist.json
> no message

- src/tokens/solana.tokenlist.json
> added MORG

- src/tokens/TheOnePiece
> add TheOnePiece

- src/tokens/solana.tokenlist.json
> Add RM coin

- src/tokens/Golden Doge Solana
---
- Token Address: 6SKogZxCWY9jKsKPMT3ChJUhQxAEeB6NjVidXQK6TEdW
- Token Name: Golden Doge Solana
- Token Symbol: GDoge
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6SKogZxCWY9jKsKPMT3ChJUhQxAEeB6NjVidXQK6TEdW/Logo.png
> Golden Doge

- src/tokens/solana.tokenlist.json
> add SOLPANDS

- src/tokens/Valknut Gold - Ticket
---
- Token Address:HHXMCAQGw4SNfwJ3FqTJdFgt2M8GqggFk9cRm4jLYPDB
- Token Name:Valknut Gold
- Token Symbol:Ticket
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/HHXMCAQGw4SNfwJ3FqTJdFgt2M8GqggFk9cRm4jLYPDB/logo.svg
- Link to the official homepage of token: https://solvikings.com/
> Create Valknut Gold - Ticket

- src/tokens/solana.tokenlist.json
- Token Address: 67Z7Pr4pX5iMczBox2bCgeU7Dy6SJRm2kZaMJoptstse
- Token Name: Komondor
- Token Symbol: $KOMO
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/67Z7Pr4pX5iMczBox2bCgeU7Dy6SJRm2kZaMJoptstse/logo.svg
- Link to the official homepage of token: https://komondor.so/
> Add Komondor Token

- src/tokens/solana.tokenlist.json
> Add BSAMO Token

- solana.tokenlist.json
- src/tokens/solana.tokenlist.json
> add serumv3usdc to extensions

- src/tokens/solana.tokenlist.json
> update token info for <SWOLE & SWOLE DOGE>

- src/tokens/solana.tokenlist.json
---
- Token Address: GPF8ZZP6y1BkGAPLvmQCzkvVHvMUBko5e1pZzh8DD87Y
- Token Name: PrimeBech
- Token Symbol: BECH
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/GPF8ZZP6y1BkGAPLvmQCzkvVHvMUBko5e1pZzh8DD87Y/logo.png
- Link to the official homepage of token: twitter.com/doesitxz
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): -
> commit for BECH & PrimeBech

- src/tokens/solana.tokenlist.json
---
- Token Address: 92ibHPyfcwQnsscwkutSP7f9yWzz6GaVHu78gyQ37L1i
- Token Name: FOMO
- Token Symbol: FOMO
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/92ibHPyfcwQnsscwkutSP7f9yWzz6GaVHu78gyQ37L1i/logo.png
- Link to the official homepage of token: https://fomokitty.com
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): -
> Added FOMO

- src/tokens/solana.tokenlist.json
> add metararity

- src/tokens/solana.tokenlist.json
---
Token Address: 8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s
Token Name: SolDoge
Token Symbol: SDOGE
Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s/logo.png
Link to the official homepage of token: https://www.soldoge.io …
> Workaround to ensure automerge succeeds.

- src/tokens/solana.tokenlist.json
> add coingeckoId for Bamboo

- src/tokens/solana.tokenlist.json
> add ink token

- src/tokens/solana.tokenlist.json
---
- Token Address: Rs3Mrx9ZSNwsTM3gtJhEbeHQdTfzcvUWHg8T8Ena3pD
- Token Name: GLUB Token
- Token Symbol: GLUB
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Rs3Mrx9ZSNwsTM3gtJhEbeHQdTfzcvUWHg8T8Ena3pD/logo.png
- Link to the official homepage of token: https://billionairewhaleclub.com/
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): -
> Added GLUB

- src/tokens/solana.tokenlist.json
---
Attaching minimum for each coin
"address": "FN3v94TgcDjae6r9TccXdrThZTy7Ya5b1PMFFdCNo9Fr",
"symbol": "FAC",
"name": "Financial Aid Coin",
"decimals": 9,
"logoURI": "https://cdn.jsdelivr.net/gh/FinancialBlock/SwyftToken/FAC.png",
"website": "http://financialaidcoin.com"
&
"address": "HPYP2WUVM8iRDG5XLzTBvcPqVcvY7eWj2Q2fEfwR51zX",
"symbol": "SC",
"name": "Swyft Coin",
"decimals": 9,
"logoURI": "https://cdn.jsdelivr.net/gh/FinancialBlock/SwyftToken/Swyft.png",
"tags": [ …
> FAC & SC commit

- src/tokens/solana.tokenlist.json
> Add VINU Token final

- src/tokens/solana.tokenlist.json
---
- Token Address: 6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY
- Token Name: SolemPad
- Token Symbol: SOLEM
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6qAJ9W5XCb2JyrTRV8bcoXa6HmHNz9YikLMWK71dH1sY/logo.png
- Link to the official homepage of token: https://www.solempad.net
> Add SOLEM token

- solana.tokenlist.json
> Updated solana.tokenlist.json

- src/tokens/solana.tokenlist.json
---
Token Address: yPRTUpLDftNej7p6QofNYgRArRXsm6Mvkzohj4bh4WM
Token Name: yPRT (Parrot Protocol)
Token Symbol: yPRT
Logo: (logo should be uploaded under assets/mainnet//*.<png/svg>)
Link to the official homepage of token: https://parrot.fi/
> Update yPRT token info

- src/tokens/solana.tokenlist.json
> added pump logo

- src/tokens/solana.tokenlist.json
> add Monster Inu

- src/tokens/solana.tokenlist.json
> PUT added token 

- src/tokens/solana.tokenlist.json
> fixing pooch

- src/tokens/solana.tokenlist.json
> add $TICKET

- src/tokens/solana.tokenlist.json
> Add GOATS token

- src/tokens/solana.tokenlist.json
> new token HNI

- solana.tokenlist.json
> Shibalana (coingeckoId)

- src/tokens/solana.tokenlist.json
> Update bookworm devnet

- src/tokens/solana.tokenlist.json
> Signed-off-by: leonidastoken <hello@leonidastoken.com>

- src/tokens/solana.tokenlist.json
- Token Address: 9K4uNquZjVSBBN6fBsp62gtYLropyAxAbdZC7D9XErih
- Token Name: Oppa
- Token Symbol: OPPA
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/9K4uNquZjVSBBN6fBsp62gtYLropyAxAbdZC7D9XErih/logo.png
- Link to the official homepage of token: https://nft.heyoppa.com/
> add oppa token

- solana.tokenlist.json
> Shibalana serum

- src/tokens/solana.tokenlist.json
---
- Token Address:HHXMCAQGw4SNfwJ3FqTJdFgt2M8GqggFk9cRm4jLYPDB
- Token Name:Valknut Gold
- Token Symbol:Ticket
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/HHXMCAQGw4SNfwJ3FqTJdFgt2M8GqggFk9cRm4jLYPDB/logo.svg
- Link to the official homepage of token: https://solvikings.com/
> Add Valknut Gold - "Ticket"

- src/tokens/solana.tokenlist.json
> Update solana.tokenlist.json add DIBU

- src/tokens/solana.tokenlist.json
add weAXS, weDYDX, weSHIB (rebase of #3859)
> add weAXS, weDYDX, weSHIB

- src/tokens/solana.tokenlist.json
- Token Address: yes
- Token Name: yes
- Token Symbol: yes
- Logo: (logo should be uploaded under assets/mainnet/<mint address>/\*.<png/svg>) yes
- Link to the official homepage of token: yes
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): yes
> SolFarm -> Tulip Rebrand 

- src/tokens/solana.tokenlist.json
Updated DXB SPL Token Address.
----
* Token Address: 8mgeCL7k2cB2KTN8NhD5biqvcbkfrmBogDpYoHmn5cKQ
* Token Name: DefiXBet
* Token Symbol: DXB
* Logo:
* Link to the official homepage of token: DefiXbet.com
our Token Address has been updated. It can be verified that this request is from our team by checking SPL Token address on DefiXBet Whitepaper slide 23
> Change DXB Token Address

- src/tokens/solana.tokenlist.json
> Add Cryowar Token

- src/tokens/solana.tokenlist.json
> add wormhole assets

- src/lib/tokenlist.ts
> feat: add Solana strategy for fetching token-list

- src/tokens/solana.tokenlist.json
> Added coingecko for aury

- src/tokens/solana.tokenlist.json
> add links for Almond token

- src/tokens/solana.tokenlist.json
> add coingeckoID

- src/tokens/solana.tokenlist.json
---
- Token Address: 6JdcMdhqgCtcP4U9tieRqmKLhPLxRMLC67QfmdXAJBvZ
- Token Name: KITTY SOLANA
- Token Symbol: KITTY
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/6JdcMdhqgCtcP4U9tieRqmKLhPLxRMLC67QfmdXAJBvZ.png
- Link to the official homepage of token: https://kittysolana.com/
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): kitty-solana
> Update KITTY Coingecko and Coinmarketcap solana.tokenlist.json

- src/tokens/solana.tokenlist.json
> Remove duplicate (and invalid) CAVE

- src/tokens/solana.tokenlist.json
> Update URL for icon

- src/tokens/solana.tokenlist.json
> Adds Saber LP tokens

- src/tokens/solana.tokenlist.json
> Try to remove nft tag

- src/tokens/solana.tokenlist.json
> add coingeckoId for CAVE

- src/tokens/solana.tokenlist.json
> solview logo update

- src/tokens/solana.tokenlist.json
> add coin gecko

- src/tokens/solana.tokenlist.json
> Add coingecko for PANDA

- src/tokens/solana.tokenlist.json
> Update MORN ticker and logo

- src/tokens/solana.tokenlist.json
> GENE market

- src/tokens/solana.tokenlist.json
> update Solit SLT on the solana.tokenlist.json

- src/tokens/solana.tokenlist.json
> update TUI logo and tags

- src/tokens/solana.tokenlist.json
> add serumV3Usdc to Invictus

- src/tokens/solana.tokenlist.json
> add SONAR coingeckoId

- src/tokens/solana.tokenlist.json
> Updates extensions to add twitter

- src/tokens/solana.tokenlist.json
> Update MSI coingeckoId

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: Foea9rMuUk58xn414yB4PfWcP2VweR2mr3SU3ZUmSEa7
- Token Name: TURNT
- Token Symbol: TURNT
- Link to the official homepage of token: https://www.turntuptikis.com/
Your pull request will be automatically merged if the following …
> remove tags $TURNT

- src/tokens/solana.tokenlist.json
> change website and instagram for Naxar

- src/tokens/solana.tokenlist.json
token network replacement
---
- Token Name:
- Your pull request **only adds new tokens** to the …
> ASL token network replacement 

- src/tokens/solana.tokenlist.json
> Update token address

- src/tokens/solana.tokenlist.json
> [important] Edit PANDA tag

- src/tokens/solana.tokenlist.json
add extensions
- "discord": "https://discord.com/invite/YRtzm69Qzd"
- "medium": "https://boba-so.medium.com"
- "telegram": "https://t.me/boba_so",
- "twitter": "https://twitter.com/boba_solana"
> BOBA - refactor: add extensions

- src/tokens/solana.tokenlist.json
> EYE logo change

- src/tokens/solana.tokenlist.json
> Quest token add tags Quest lp token address change

- src/tokens/solana.tokenlist.json
> refactor: website, twitter

- src/tokens/solana.tokenlist.json
> logo change

- src/tokens/solana.tokenlist.json
> Update extensions DRINK token

- src/tokens/solana.tokenlist.json
> Update TRTLS Token

- src/tokens/solana.tokenlist.json
> Update $KYO Token

- src/tokens/solana.tokenlist.json
> update DAWG token

- src/tokens/solana.tokenlist.json
> Shibalana serumV3Usdc

- src/tokens/solana.tokenlist.json
> Removed NFT tag

- src/tokens/solana.tokenlist.json
for avoidance of confusion in wallets/scanners, this PR renames wormhole v1 tokens (as matched by bridgeContract) to have:
* symbol end with "_v1"
* name end with "(Wormhole v1)"
the PR is split into 3 commits for ease of understanding.  
* the first commit cleans up a few ascii related issues
* the second one automatically fixes most of the tokens
* the last one fixes a few that violated standards previously.
a script that accomplished this migration follows:
```
import json
import os
from collections import OrderedDict
dir_path = os.path.dirname(os.path.realpath(__file__))
json_path = os.path.join(dir_path, "solana.tokenlist.json")
f = open(json_path, 'r')
data = json.load(f, object_pairs_hook=OrderedDict)
token_list = data['tokens']
prereq_exceptions = []
partials = []
done = [] …
```
> rename wormholeV1 symbols

- src/tokens/solana.tokenlist.json
> add starlaunch coingeckoid

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: 2HeykdKjzHKGm2LKHw8pDYwjKPiFEoXAz74dirhUgQvq
- Token Name: Sator
- Token Symbol: SAO
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/2HeykdKjzHKGm2LKHw8pDYwjKPiFEoXAz74dirhUgQvq/Sator_Logo.png
- Link to the official homepage of token: https://sator.io
- Coingecko ID if available (https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id_): sator
Your pull request …
> updated metadata for sator token

- src/tokens/solana.tokenlist.json
> Update Twitter account

- src/tokens/solana.tokenlist.json
> Partner Coin added coingeckoid and discord link

- src/tokens/solana.tokenlist.json
> Update MIM Symbol

- src/tokens/solana.tokenlist.json
> Change Token Tag From NFT to Utility

- src/tokens/solana.tokenlist.json
> Updating LNFTxLIQ token

- src/tokens/solana.tokenlist.json
> Pit Coin logo fix

- src/tokens/solana.tokenlist.json
> Updated Logo

- src/tokens/solana.tokenlist.json
> Solanyx token update

- src/tokens/solana.tokenlist.json
> Change token symbol and name

- src/tokens/solana.tokenlist.json
> VIBE decimals change

- src/tokens/solana.tokenlist.json
> Delete token from the list

- src/tokens/solana.tokenlist.json
> Update Samusky solana.tokenlist.json 3.0

- src/tokens/solana.tokenlist.json
> change token GG

- src/tokens/solana.tokenlist.json
> Change VIBES "nft" tag to "game" to fix display in Phantom

- src/tokens/solana.tokenlist.json
------
------
------
PRs are reviewed in bulk and and can take up to two weeks to be merged.
This repository is managed using an auto merge action. Please ensure your PR has no deleted lines, and it will be merged.
- Token Name:
- Logo: (logo should be uploaded under assets/mainnet//*.<png/svg>)
-  Your pull request only adds new tokens to the list. Any modification to existing …
> Update SYP Token Logo

- src/tokens/solana.tokenlist.json
> update Crypto King Coin token image

- src/tokens/solana.tokenlist.json
Please note: This repository is being rebuilt to accept the new volume of token additions and modifications. PR merges will be delayed.
---
---
---
- Token Name:
Your pull request will …
> fix icon for Fresh Token

- src/tokens/solana.tokenlist.json
update our floki website.
---
---
---
- Token Name:
- Your pull request **only adds new tokens** to …
> update floki website

- src/tokens/solana.tokenlist.json
> update Dekadus Token

- src/tokens/solana.tokenlist.json
> Correction to PR# 8887 - CA93 Token info update

- src/tokens/solana.tokenlist.json
> update logo path

- src/tokens/solana.tokenlist.json
> remove information that not owned from DRW token

- src/tokens/solana.tokenlist.json
> remove obviously invalid address added in #8791

- src/tokens/solana.tokenlist.json
> Update Metamounts CoingeckoId

- src/tokens/solana.tokenlist.json
> Renamed token due to duplicated name

- src/tokens/solana.tokenlist.json
> Singularize Gems as Gem in the name

- src/tokens/solana.tokenlist.json
> Update solana.tokenlist.json - SocialCoin Address

- automerge/schema.cue
similar to #9328 and #9330, sorry for all of the spam
> one more addendum to #9308

- src/tokens/solana.tokenlist.json
> why won't it let me update Just Chillin & Just Darknet

- src/tokens/solana.tokenlist.json
* add serumV3Usdc markets for ETH, BNB, SUSHI, LINK
* fix coingecko links for ETH, BNB, CAKE
* correct symbol and name for DAI
* correct name for QUICK
> add serumV3Usdc markets for ETH, BNB, SUSHI, LINK

- src/tokens/solana.tokenlist.json
> my QMC Token remove extentions

- src/tokens/solana.tokenlist.json
> change NFT tag

- src/tokens/solana.tokenlist.json
> Dintcoin extensions

- src/tokens/solana.tokenlist.json
> Delete NOLE NPC

- src/tokens/solana.tokenlist.json
Update my token Twitter and website
---
---
---
- Token Name:
- Your pull request **only adds new …
> update token information

- src/tokens/solana.tokenlist.json
> Shiba Poker Coin Token logo

- src/tokens/solana.tokenlist.json
> Update DIBU Coin

- src/tokens/solana.tokenlist.json
> added coingeckoId to PRISM

- src/tokens/solana.tokenlist.json
> Remove deprecated AUDIO (Wormhole V1)

- src/tokens/solana.tokenlist.json
> update RAD token tags

- src/tokens/solana.tokenlist.json
> fixed logo URI

- src/tokens/solana.tokenlist.json
> correcting broken link to GYRC logo

- src/tokens/solana.tokenlist.json
> remove PineappleCoin test token

- src/tokens/solana.tokenlist.json
> fix COMP address

- src/tokens/solana.tokenlist.json
> update racefi social

- src/tokens/solana.tokenlist.json
> Solanyx info update

- src/tokens/solana.tokenlist.json
> modify number of decimals GOATS

- src/tokens/solana.tokenlist.json
> Edit SQR token name

- src/tokens/solana.tokenlist.json
> fix chb adress

- src/tokens/solana.tokenlist.json
> update website, twitter and logo for PTR

- src/tokens/solana.tokenlist.json
> Update GTA token details

- src/tokens/solana.tokenlist.json
> updated Staked Sol Invictus

- src/tokens/solana.tokenlist.json
> Update GMI and GGMI token urls

- src/tokens/solana.tokenlist.json
Reverts solana-labs/token-list#9075
> Revert "Update GTA token details"

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address:GHP2CEPaawZkkDqhq4i8HGJV1TAJ3uati5RFDa6zGmC6
- Token Name:MTMS Network
- Token Symbol:MTMS
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/GHP2CEPaawZkkDqhq4i8HGJV1TAJ3uati5RFDa6zGmC6/logo.png
- Link to the official homepage of token:https://mtms.live
Your pull request will be …
> Update MTMS token name and website

- src/tokens/solana.tokenlist.json
> Update logo URL for RunGoodKoin

- src/tokens/solana.tokenlist.json
> Update WEENS token

- src/tokens/solana.tokenlist.json
I'm submitting a ...
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project
Summary
Hello, I would like to delete my token from list because of the issue with phantom wallet. It recognizes token as NFT. I just sent pull request Delete token from the list https://github.com/solana-labs/token-list/pull/7063.
Thank you
seems same issue as https://github.com/solana-labs/token-list/issues/8280
> removed tiny token from token list because of phantom wallet issue

- src/tokens/solana.tokenlist.json
> Delete the old token from the list

- src/tokens/solana.tokenlist.json
> kingsolo token name error updated

- src/tokens/solana.tokenlist.json
> removing my tokens with error

- src/tokens/solana.tokenlist.json
> Change BLCK logo

- src/tokens/solana.tokenlist.json
> change tags of atlasdex token

- src/tokens/solana.tokenlist.json
> Add coingeckoId to BLOCK token

- src/tokens/solana.tokenlist.json
> Delete USDL token

- src/tokens/solana.tokenlist.json
> Delete Lag token

- src/tokens/solana.tokenlist.json
Reverts solana-labs/token-list#12314
> Revert "Delete Lag token"

- src/tokens/solana.tokenlist.json
> Added extentions and tags to BreezyModels Coin (BZML)

- src/tokens/solana.tokenlist.json
remove 3fBzUqm2tJuWVUHSBVULBS6W8FGcMiszMyuCdsddrqFZ which user was trying to delete in #12314
> remove 3fBzUqm2tJuWVUHSBVULBS6W8FGcMiszMyuCdsddrqFZ

- src/tokens/solana.tokenlist.json
> Update VITAL links and decimals

- src/tokens/solana.tokenlist.json
> Remove false name

- src/tokens/solana.tokenlist.json
> Update Sinner Token to remove tags

- src/tokens/solana.tokenlist.json
> add coingecko id

- src/tokens/solana.tokenlist.json
> Add tokens and remove fake Katana

- src/tokens/solana.tokenlist.json
> Modified decimals specified for WebCanCoin token.

- src/tokens/solana.tokenlist.json
URL Change
---
---
---
- Token Name:
- Your pull request **only adds new tokens** to the list. Any …
> URL Change

- src/tokens/solana.tokenlist.json
> Update brainyapegang token uri path

- src/tokens/solana.tokenlist.json
> website link update nanX - nanoX

- src/tokens/solana.tokenlist.json
> Updating logo

- src/tokens/solana.tokenlist.json
> Update: Add coingeckID for Cry Coin

- src/tokens/solana.tokenlist.json
> Xar Logo Change

- src/tokens/solana.tokenlist.json
> added extensions to TheSolanDAO token

- src/tokens/solana.tokenlist.json
> Update token name 

- src/tokens/solana.tokenlist.json
> Add Coingecko id for TabTrader Token

- src/tokens/solana.tokenlist.json
@keone Seems like there is an issue while json parsing with following parameters:
serumV3Usdc
coingeckoId
Could you please look into it. I just added serum id , coingeckoId is also not parsing!
Yes the input fields are correctly enumerated!
> Add serum id for parasol

- src/tokens/solana.tokenlist.json
We are currently working on a token that needed its social sites to be added to the token. 
Updates where-made to the existing token metadata.
> Social Media Files Updated

- src/tokens/solana.tokenlist.json
> added coinGeckoId for TheSolanDAO token

- src/tokens/solana.tokenlist.json
> change logo url

- src/tokens/solana.tokenlist.json
> Update Mudo coin

- src/tokens/solana.tokenlist.json
@keone Just went through rebranding so had to update all the links, please merge it manually.
> Updated all the links for parasol

- src/tokens/solana.tokenlist.json
> changessssss

- src/tokens/solana.tokenlist.json
> removed excess tags

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: 1SSBwC8hxB4GXzKKU4ENNpST7zgpTmucDe9NoAopWXX
- Token Name: Irish Setter Sol
- Token Symbol: ISS
- Logo: https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/1SSBwC8hxB4GXzKKU4ENNpST7zgpTmucDe9NoAopWXX/logo.png
- Link to the official homepage of token: https://irishsetter.io
Your pull …
> Update Discord Link

- src/tokens/solana.tokenlist.json
> add coingeckoId to $SVT

- src/tokens/solana.tokenlist.json
> Fixed logo for HYPE

- src/tokens/solana.tokenlist.json
> updated fanalyst symbol

- src/tokens/solana.tokenlist.json
> Update solana.tokenlist.json to remove imposter

- src/tokens/solana.tokenlist.json
> Add relevant SHDW listing info

- src/tokens/solana.tokenlist.json
> Update Fella Coin to Council Coin

- src/tokens/solana.tokenlist.json
> update SNS address

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address:  3xXMjiMyu4hthrVWmsxvBrKtehBWFgSKRnGB9Je4mmdA and 4rEYp4rKAHZwiKmaTi8dUNgSZnNtkMAMEjqRFvCeuaT7
- Token Name: Singularity and Velorum
- Token Symbol: SINGULARITY and VELORUM
- Logo: Not changed
- Link to the official homepage of token: https://singularityonline.app
- Coingecko ID if available: N/A
- Your pull request **only adds …
> Adds social ext for `SINGULARITY` and `VELORUM` in mainnet and devnet

- src/tokens/solana.tokenlist.json
#14646 
#14649 
added by @ODENSAMAOG in https://github.com/solana-labs/token-list/commit/63dbee7e67e3f57b1f016a105d42b49272302cd3
> rem Gx54wvBd9n5LwtAgBC8n125ty96KEEFFedMD5Vqs3idk per #14646 & #14649

- src/tokens/solana.tokenlist.json
> fix: place coingeckoId at the right place

- src/tokens/solana.tokenlist.json
> add coingecko and links

- src/tokens/solana.tokenlist.json
Add Coingecko ID  babytigergold
> update COINGECKO ID

- src/tokens/solana.tokenlist.json
> COINK changed name

- src/tokens/solana.tokenlist.json
> Update Coingecko and CoinMarketCap links

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: UXPhBoR3qG4UCiGNJfV7MqhHyFqKN68g45GoYvAeL2M
- Token Name: UXDProtocol Governance Token
- Token Symbol: UXP
- Link to the official homepage of token: uxd.fi
Your pull request will be automatically merged if the following conditions …
> Update UXP coingecko and cmc ids. Removes the tags.

- src/tokens/solana.tokenlist.json
> update token list

- src/tokens/solana.tokenlist.json
> Adding website

- src/tokens/solana.tokenlist.json
> Change address for LSTAR token

- src/tokens/solana.tokenlist.json
> UXS change of logo URI

- src/tokens/solana.tokenlist.json
> Updated social channels for LIT token

- src/tokens/solana.tokenlist.json
> updated pegcoin

- src/tokens/solana.tokenlist.json
Tag don't work well with phantom wallet. makes the coin show as a NFT instead of a token
---
---
---
- Token Name:
Your pull request will be automatically merged if the following …
> Update Tags in artchive coins

- src/tokens/solana.tokenlist.json
> Updated FAB, fUSD, fURA mints and added fXAU devnet

- src/tokens/solana.tokenlist.json
> Changed logo url for SDO token

- src/tokens/solana.tokenlist.json
> Update XART again

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: EGiWZhNk3vUNJr35MbL2tY5YD6D81VVZghR2LgEFyXZh
- Token Name: BIT Token
- Token Symbol: BIT
- Your pull …
> Updating BIT

- src/tokens/solana.tokenlist.json
> correct BOKU coin name

- src/tokens/solana.tokenlist.json
> update ula  logo address

- src/tokens/solana.tokenlist.json
> adding market info

- src/tokens/solana.tokenlist.json
> Update LSTAR address

- src/tokens/solana.tokenlist.json
> Updated Bill token name

- src/tokens/solana.tokenlist.json
> updating Name and add Tags

- src/tokens/solana.tokenlist.json
> update human gecko and cmc

- src/tokens/solana.tokenlist.json
> Add New Logo Sweet

- src/tokens/solana.tokenlist.json
Added CoingeckID and others links
---
---
---
- Token Name:
- Your pull request **only adds new …
> Clash Of Cars Token Added Coingecko and Other Useful Links

- src/tokens/solana.tokenlist.json
> update ammo info

- src/tokens/solana.tokenlist.json
> Updating COOP token with name CoopBits and social media

- src/tokens/solana.tokenlist.json
> Rename traits to treats

- src/tokens/solana.tokenlist.json
> update website link for metacopsnft.io token

- src/tokens/solana.tokenlist.json
> I need to update my token address (manual review)

- src/tokens/solana.tokenlist.json
Updated assets to link to my own repo so they populate correctly
> fix: updated to our own assets

- src/tokens/solana.tokenlist.json
> BlockchainWizard Symbol Change

- src/tokens/solana.tokenlist.json
> SEFU token url logo change

- src/tokens/solana.tokenlist.json
adding coingeckoId
---
---
---
- Token Name:
- Your pull request **only adds new tokens** to the …
> swanlana update

- src/tokens/solana.tokenlist.json
Removing the token I authored since it is wrongly recognized by Phantom.
> Delete token from the list.

- src/tokens/solana.tokenlist.json
> Update Tags & Extensions Ravaverse

- src/tokens/solana.tokenlist.json
> update token symbol

- src/tokens/solana.tokenlist.json
Hey @keone i added some links to this token #17231 no modification/deletion done by me. Please merge it manually! Thanks.
>  Add website & twitter  for meta4 (**manual merge required)

- src/tokens/solana.tokenlist.json
> remove coingeckoid from mount

- src/tokens/solana.tokenlist.json
**Apologies**, I misnamed this token in my original commit - https://github.com/solana-labs/token-list/commit/4b80d64295e2e9e001d73f58cf7d1708e911fcd9
---
---
---
- Token Name:
Your …
> Amend $GBT token name

- src/tokens/solana.tokenlist.json
> update ula and zkl token address

- src/tokens/solana.tokenlist.json
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>
---
---
---
- Token Name:
- Your pull request …
> TINY metadata updates

- src/tokens/solana.tokenlist.json
> Updating website and social media

- src/tokens/solana.tokenlist.json
> @keone Update Memoria URL

- src/tokens/solana.tokenlist.json
> Update Zion Coin

- src/tokens/solana.tokenlist.json
> update ula logo address

- src/tokens/solana.tokenlist.json
> restructurization 

- src/tokens/solana.tokenlist.json
> Update Logo URL to match image name

- src/tokens/solana.tokenlist.json
> REMOVE nft tag for cPANZR

- src/tokens/solana.tokenlist.json
> Extensions update

- src/tokens/solana.tokenlist.json
> ARTE coingecko added

- src/tokens/solana.tokenlist.json
> Change FAKE Address to Mainnet address

- src/tokens/solana.tokenlist.json
> Update solana.tokenlist.json to include coingeckoID for the sRLY token

- src/tokens/solana.tokenlist.json
> Update to remove tags

- src/tokens/solana.tokenlist.json
Please allow me to make this changes, thank you so much
---
---
---
- Token Name:
- Your pull …
> Update Name and Links

- src/tokens/solana.tokenlist.json
> [Update] Glide meta data

- src/tokens/solana.tokenlist.json
> Changing RICE name

- assets/mainnet/7TFkZszsBijKKdxhLn2PkTJsbBv8a9CfsB61LsSFQmnZ/logo.svg
> replace PHORK logo

- src/tokens/solana.tokenlist.json
> Update Token for correct # of decimals

- src/tokens/solana.tokenlist.json
> Changed decimal places to 9 to CFT Token

- src/tokens/solana.tokenlist.json
> Add $SHARDS token

- src/tokens/solana.tokenlist.json
> Update MOSC issue

- src/tokens/solana.tokenlist.json
> Correction URL Stone Coin

- src/tokens/solana.tokenlist.json
> add stablecoin tag to UST

- src/tokens/solana.tokenlist.json
> Quest token website change

- src/tokens/solana.tokenlist.json
Hi there, I mistakenly created a token with decimal before.
Just need to replace the token address and decimal points. Thx.
> Change MYSTIC token address and decimal

- src/tokens/solana.tokenlist.json
> Flappyz image & tags update

- src/tokens/solana.tokenlist.json
> Update AD2 Logo

- src/tokens/solana.tokenlist.json
> AvocadoCoin: Add Telegram, CoinGecko and CoinMarketCap Info

- src/tokens/solana.tokenlist.json
> Add coingeckoid to DARC token

- src/tokens/solana.tokenlist.json
> Modified LAZY Token image uri

- src/tokens/solana.tokenlist.json
> Change chain for PlebCoin

- src/tokens/solana.tokenlist.json
> add AUDIO serum market

- src/tokens/solana.tokenlist.json
> Update SLGT Token

- src/tokens/solana.tokenlist.json
> AvocadoCoin Update Tags (Remove Security-Token label error)

- src/tokens/solana.tokenlist.json
> [Extensions Update] Token CHIMP

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: 
- Token Name:
- Your pull request **only adds new tokens** to the list. Any …
> updating extensions and qubit logo

- src/tokens/solana.tokenlist.json
updating symbol name moosecoin and llamacoin
---
---
---
- Token Name:
- Your pull request **only …
> updating symbol name moosecoin and llamacoin

- src/tokens/solana.tokenlist.json
…. I am a dummy and did not do this the first time around.
---
---
---
- Token Name:
- Your pull …
> Fixed Image Link for GoobyQuest plus added a description for the coin. 

- src/tokens/solana.tokenlist.json
> Remove nft tag from tokens

- src/tokens/solana.tokenlist.json
Remove "nft" from tags
---
---
---
- Token Name:
- Your pull request **only adds new tokens** to the …
> Removing a tag from token

- src/tokens/solana.tokenlist.json
> WEBSITE FIX

- src/tokens/solana.tokenlist.json
> Changed logoURI of MolleCoin

- src/tokens/solana.tokenlist.json
> update commit for Fm9rHUTF5v3hwMLbStjZXqNBBoZyGriQaFM6sTFz3K8A

- src/tokens/solana.tokenlist.json
> updated logo url

- src/tokens/solana.tokenlist.json
> coingecko id added

- src/tokens/solana.tokenlist.json
> Update WLZVC Token

- src/tokens/solana.tokenlist.json
fix Bhjc5ezhrKnZrLbMGahuY5rBYJ3ViKNFMsa7kNBnpacw logoUri for #18110 #19919
> fix Bhjc5ezhrKnZrLbMGahuY5rBYJ3ViKNFMsa7kNBnpacw logoUri

- src/tokens/solana.tokenlist.json
> add website and social media details to REO token

- src/tokens/solana.tokenlist.json
> Full refresh sunlight token

- src/tokens/solana.tokenlist.json
#20438
#20506
manual fix for 9t6F4UJXr9B4xzoSmgC9LwYHb87maYeM58PsoXgNjyVW
> manual fix for 9t6F4UJXr9B4xzoSmgC9LwYHb87maYeM58PsoXgNjyVW for #20438

- src/tokens/solana.tokenlist.json
> Modify XSGD parameters

- src/tokens/solana.tokenlist.json
> Require Manual Merge : Edited Token name

- src/tokens/solana.tokenlist.json
> Adding Coingecko and CMC listing

- src/tokens/solana.tokenlist.json
> correct serum markets for droplets launched on 7th March

- src/tokens/solana.tokenlist.json
---
---
---
- Token Address: 6LaJKhZts2cJJPdo9v7XR4kHiLk9ERh16VLKjBUS8DxD
- Token Name: Lilypad Token
- Token Symbol: $LILY
- Link to the official homepage of token: https://frog.party/
Your pull request will be automatically merged if the following …
> change lily spl address

- src/tokens/solana.tokenlist.json
> update token symbol *(manual merge required)

- src/tokens/solana.tokenlist.json
> SerumV3Usdc added for vidi

- src/tokens/solana.tokenlist.json
> Add usd-coin coingeckoId to USDC-Dev coin

- src/tokens/solana.tokenlist.json
> add PsyOptions coingecko id

- automerge/schema.cue
> wormhole -> portal

- src/lib/tokenlist.ts
change CDNTokenListResolutionStrategy to point to token-list@latest per https://github.com/jsdelivr/jsdelivr/issues/18384
> change CDNTokenListResolutionStrategy to point to token-list@latest

- src/tokens/solana.tokenlist.json
> Add coingeckoId to HIRAM

- README.md
Added deprecation info on how to create/add/update token metadata using the new standard for those who find themselves at this repo in the future.
Goal: Archive repo June 20th, 2022
> feat: add deprecated information
