solana-labs/token-list

- src/tokens/mainnet-beta.json
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updating token symbol and name
- **What is the current behavior?** (You can also link to an open issue here)
display token name as Benchmark and symbol as Mark
- **What is the new behavior (if this is a feature change)?**
Display token name as Standard and symbol as xMark
- **Other information**:
None
> Change token name and symbol for Mark

- src/lib/tokenlist.spec.ts
- src/lib/tokenlist.ts
I was writing some code integrating with `TokenListProvider`, to my surprise it returns the entire original `TokenListContainer` when the slug does not exist. That's not great, I propose to raise instead. However, I am not sure what type of Error it should be...
Or maybe return an empty array, that would make it similar to a regular `.filter`
> Throw when slug does not exist

- src/tokens/solana.tokenlist.json
* Token Address:  4pk3pf9nJDN1im1kNwWJN1ThjE8pCYCTexXYGyFjqKVf
* Token Name: Dominican Pesos
* Token Symbol: oDOP
* Logo
* Link to the official homepage of token: https://Odop.io/
oDOP is a stable coin based on Dominican Peso, the official currency of Dominican Republic.
The oDOP cryptocurrency works with a single entity OuroSRL which is the sole minter of the oDOP token. Traders that mint/redeem oDOP are subject to KYC/AML checks and only after having passing those then they can purchase or redeem the oDOP token. Sales of oDOP for fiat currencies only occur in the Dominican Republic.
> Added oDop to tokenlist

- src/tokens/solana.tokenlist.json
Working on sollet.io usage of token-list i noticed that Wrapped SOL shows as Solana. This is so it shows the same as mainnet-beta or testnet.
> Wrapped sol for devnet too

- src/tokens/solana.tokenlist.json
The STEP Logo is listed incorrectly as a `.jpg` and should be a `.png`.
> fix: change step token to png

- src/tokens/solana.tokenlist.json
The new COPE has 6 decimals (not 0)
> Fix new cope decimals

- src/tokens/solana.tokenlist.json
Decimals should be 0
https://explorer.solana.com/address/2prC8tcVsXwVJAinhxd2zeMeWMWaVyzPoQeLKyDZRFKd
* Token Name: 
* Logo
> Fix mango market caps decimals in tokenlist.json

- src/tokens/solana.tokenlist.json
The reason for the change is we've failed to deliver the airdrop properly using the old one.
> Change ECOP Token Account

- src/lib/tokenlist.spec.ts
- src/tokens/solana.tokenlist.json
> feat: add check for duplicates

- src/tokens/solana.tokenlist.json
[waterfallbot](https://t.me/CENTRALwaterfall) now support realtime tracking trades of SPL tokens on SerumV3
We include waterfallbot url of tokens as an extension so other parties like solanabeach, solscan ... can display it in token page
Supported tokens:
Thank you
> update waterfallbot url for SPL tokens

- src/tokens/solana.tokenlist.json
The PAI mint address `Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS` can be seen in our official security documentation:
https://doc.partyparrot.finance/security/mainnet.html#debttype
> Add PAI (Parrot Stablecoin)

- src/tokens/solana.tokenlist.json
Accidentally submitted wrong address for the $DGEN token
> Replace incorrect SRM market address with correct mint address

- src/tokens/solana.tokenlist.json
- I will not ping the Discord about this pull request.
FIX: "tags" field is missing on renBTC (CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5)
> fix: add missing "tags" field to renBTC

- src/lib/tokenlist.ts
This would allow static strategy `.resolve` to be used synchronously.
> fix: resolve to not be async when it is not needed

- src/tokens/solana.tokenlist.json
This PR adds the `coingeckoId` extension for Sunny Aggregator.
This data was not available when #811 was merged, and this PR avoids the merge conflict and duplicate icon that's blocking #850.
> Add coingeckoId extension for Sunny Aggregator

- src/tokens/solana.tokenlist.json
Wrong picture extension as mentioned in the creation pull request: https://github.com/solana-labs/token-list/pull/552#issuecomment-881291383
This pull request only edits the extention.
----
* Token Name: 
> EDIT LRA token

- src/tokens/solana.tokenlist.json
Cheems had the wrong decimal set in the file, corrected it now.
> Cheems token decimal correction

- src/tokens/solana.tokenlist.json
Improvements split into 2 commits for clarity:
1. reformat whitespace only (no changes to dictionary structure) for consistency and clarity
2. move ~20 token definitions into the `tokens` list element (were mistakenly added one level too high starting with `BPCoin`)
> correct 20 token definitions' location in dict

- .github/workflows/build.yml
- src/tokens/schema.cue
- src/tokens/solana.tokenlist.json
- src/tokens/validate.sh
This adds a Cue schema for the token list JSON file, derived
from the Uniswap JSON Schema.
Made some judgement calls on whether to clean up the data or
extend the schema to make it fit. In particular,
no symbols were changed since it's not clear whether anyone relies
on immutable symbol names, even though some of them are
*really* invalid. In a similar vein, we should consider pruning
the number of valid extensions - no explorer will possibly show
a dozen different types of external links.
> Add schema and carefully clean up existing data

- automerge/schema.cue
e.g. https://github.com/solana-labs/token-list/pull/5915/files fails because of the `+` in the url
> automerge.go: telegram urls can apparently contain +s

- src/tokens/solana.tokenlist.json
The recent PR #5918 to add the BAD token introduced malformed JSON that
breaks parsers of the file. JSON does not allow trailing commas in
objects (see https://json.org). This patch fixes the JSON format to be
readable once more.
> fix BAD json

- src/tokens/solana.tokenlist.json
Phisher re-committed their scam token. We need to rename to prevent auto re-add.
> Renamed scam token to prevent people from visitting phishing website.

- src/tokens/solana.tokenlist.json
addendum to #9308, token blanked out needs to have nonempty symbol to avoid causing failures for other commits
> addendum to #9308, token blanked out needs to have nonempty symbol

- .github/workflows/main.yml
Fixes https://github.com/solana-labs/token-list/issues/8358
Turns out `assets` indeed are not supposed to be included in the package.
However, since so far `token-list` was being published with `yarn`, it was suffering from a `yarn` bug, which makes it not handle ignored and unignored files properly if there is a negative expression in `package.json#files` (there are numerous issues with confused people in Yarn repo, one of them — https://github.com/yarnpkg/yarn/issues/8332).
This pull request proposes changes publishing command from `yarn publish` to `npm publish` which in itself isn't a huge change (the effect should be the same), but since we'll be using NPM to pack the tarball files will be properly included/excluded and the resulting package will be 5.6 MB unpacked instead of >200 …
> Publish package with `npm` instead of `yarn`

- src/tokens/solana.tokenlist.json
update OHM to OHM_v1 due to olympus migration, see https://docs.olympusdao.finance/main/basics/migration
> update OHM to OHM_v1 due to olympus migration

- src/lib/tokenlist.ts
Sometimes the endpoint (eg. https://token-list.solana.com/solana.tokenlist.json) returns an empty response (eg. a literal `{}`). In cases like that, `tokenlist.tokens` will be `undefined`.
* When `tokens` is `undefined`, default to an empty array so that the rest of the program doesn't fatal.
> fix: protect against the `tokens` property` being `undefined`
